// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: task_service.proto
// Protobuf C++ Version: 5.29.5

#include "task_service.pb.h"

#include <algorithm>
#include <type_traits>
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/generated_message_tctable_impl.h"
#include "google/protobuf/extension_set.h"
#include "google/protobuf/generated_message_util.h"
#include "google/protobuf/wire_format_lite.h"
#include "google/protobuf/descriptor.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/reflection_ops.h"
#include "google/protobuf/wire_format.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"
PROTOBUF_PRAGMA_INIT_SEG
namespace _pb = ::google::protobuf;
namespace _pbi = ::google::protobuf::internal;
namespace _fl = ::google::protobuf::internal::field_layout;
namespace task {
              template <typename>
PROTOBUF_CONSTEXPR TaskResponse_IterationOutputsEntry_DoNotUse::TaskResponse_IterationOutputsEntry_DoNotUse(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : TaskResponse_IterationOutputsEntry_DoNotUse::MapEntry(_class_data_.base()){}
#else   // PROTOBUF_CUSTOM_VTABLE
    : TaskResponse_IterationOutputsEntry_DoNotUse::MapEntry() {
}
#endif  // PROTOBUF_CUSTOM_VTABLE
struct TaskResponse_IterationOutputsEntry_DoNotUseDefaultTypeInternal {
  PROTOBUF_CONSTEXPR TaskResponse_IterationOutputsEntry_DoNotUseDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~TaskResponse_IterationOutputsEntry_DoNotUseDefaultTypeInternal() {}
  union {
    TaskResponse_IterationOutputsEntry_DoNotUse _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 TaskResponse_IterationOutputsEntry_DoNotUseDefaultTypeInternal _TaskResponse_IterationOutputsEntry_DoNotUse_default_instance_;

inline constexpr TaskRequest::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : environment_data_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        function_name_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        ir_data_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        ir_format_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        task_id_{::int64_t{0}},
        start_{::int64_t{0}},
        end_{::int64_t{0}},
        step_{::int64_t{0}},
        environment_size_{::uint64_t{0u}},
        _cached_size_{0} {}

template <typename>
PROTOBUF_CONSTEXPR TaskRequest::TaskRequest(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(::_pbi::ConstantInitialized()) {
}
struct TaskRequestDefaultTypeInternal {
  PROTOBUF_CONSTEXPR TaskRequestDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~TaskRequestDefaultTypeInternal() {}
  union {
    TaskRequest _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 TaskRequestDefaultTypeInternal _TaskRequest_default_instance_;

inline constexpr TaskResponse::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : iteration_outputs_{},
        result_data_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        error_message_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        task_id_{::int64_t{0}},
        result_size_{::uint64_t{0u}},
        success_{false},
        _cached_size_{0} {}

template <typename>
PROTOBUF_CONSTEXPR TaskResponse::TaskResponse(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(::_pbi::ConstantInitialized()) {
}
struct TaskResponseDefaultTypeInternal {
  PROTOBUF_CONSTEXPR TaskResponseDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~TaskResponseDefaultTypeInternal() {}
  union {
    TaskResponse _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 TaskResponseDefaultTypeInternal _TaskResponse_default_instance_;
}  // namespace task
static constexpr const ::_pb::EnumDescriptor**
    file_level_enum_descriptors_task_5fservice_2eproto = nullptr;
static constexpr const ::_pb::ServiceDescriptor**
    file_level_service_descriptors_task_5fservice_2eproto = nullptr;
const ::uint32_t
    TableStruct_task_5fservice_2eproto::offsets[] ABSL_ATTRIBUTE_SECTION_VARIABLE(
        protodesc_cold) = {
        ~0u,  // no _has_bits_
        PROTOBUF_FIELD_OFFSET(::task::TaskRequest, _internal_metadata_),
        ~0u,  // no _extensions_
        ~0u,  // no _oneof_case_
        ~0u,  // no _weak_field_map_
        ~0u,  // no _inlined_string_donated_
        ~0u,  // no _split_
        ~0u,  // no sizeof(Split)
        PROTOBUF_FIELD_OFFSET(::task::TaskRequest, _impl_.task_id_),
        PROTOBUF_FIELD_OFFSET(::task::TaskRequest, _impl_.start_),
        PROTOBUF_FIELD_OFFSET(::task::TaskRequest, _impl_.end_),
        PROTOBUF_FIELD_OFFSET(::task::TaskRequest, _impl_.step_),
        PROTOBUF_FIELD_OFFSET(::task::TaskRequest, _impl_.environment_data_),
        PROTOBUF_FIELD_OFFSET(::task::TaskRequest, _impl_.environment_size_),
        PROTOBUF_FIELD_OFFSET(::task::TaskRequest, _impl_.function_name_),
        PROTOBUF_FIELD_OFFSET(::task::TaskRequest, _impl_.ir_data_),
        PROTOBUF_FIELD_OFFSET(::task::TaskRequest, _impl_.ir_format_),
        PROTOBUF_FIELD_OFFSET(::task::TaskResponse_IterationOutputsEntry_DoNotUse, _impl_._has_bits_),
        PROTOBUF_FIELD_OFFSET(::task::TaskResponse_IterationOutputsEntry_DoNotUse, _internal_metadata_),
        ~0u,  // no _extensions_
        ~0u,  // no _oneof_case_
        ~0u,  // no _weak_field_map_
        ~0u,  // no _inlined_string_donated_
        ~0u,  // no _split_
        ~0u,  // no sizeof(Split)
        PROTOBUF_FIELD_OFFSET(::task::TaskResponse_IterationOutputsEntry_DoNotUse, _impl_.key_),
        PROTOBUF_FIELD_OFFSET(::task::TaskResponse_IterationOutputsEntry_DoNotUse, _impl_.value_),
        0,
        1,
        ~0u,  // no _has_bits_
        PROTOBUF_FIELD_OFFSET(::task::TaskResponse, _internal_metadata_),
        ~0u,  // no _extensions_
        ~0u,  // no _oneof_case_
        ~0u,  // no _weak_field_map_
        ~0u,  // no _inlined_string_donated_
        ~0u,  // no _split_
        ~0u,  // no sizeof(Split)
        PROTOBUF_FIELD_OFFSET(::task::TaskResponse, _impl_.task_id_),
        PROTOBUF_FIELD_OFFSET(::task::TaskResponse, _impl_.success_),
        PROTOBUF_FIELD_OFFSET(::task::TaskResponse, _impl_.result_data_),
        PROTOBUF_FIELD_OFFSET(::task::TaskResponse, _impl_.result_size_),
        PROTOBUF_FIELD_OFFSET(::task::TaskResponse, _impl_.error_message_),
        PROTOBUF_FIELD_OFFSET(::task::TaskResponse, _impl_.iteration_outputs_),
};

static const ::_pbi::MigrationSchema
    schemas[] ABSL_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
        {0, -1, -1, sizeof(::task::TaskRequest)},
        {17, 27, -1, sizeof(::task::TaskResponse_IterationOutputsEntry_DoNotUse)},
        {29, -1, -1, sizeof(::task::TaskResponse)},
};
static const ::_pb::Message* const file_default_instances[] = {
    &::task::_TaskRequest_default_instance_._instance,
    &::task::_TaskResponse_IterationOutputsEntry_DoNotUse_default_instance_._instance,
    &::task::_TaskResponse_default_instance_._instance,
};
const char descriptor_table_protodef_task_5fservice_2eproto[] ABSL_ATTRIBUTE_SECTION_VARIABLE(
    protodesc_cold) = {
    "\n\022task_service.proto\022\004task\"\267\001\n\013TaskReque"
    "st\022\017\n\007task_id\030\001 \001(\003\022\r\n\005start\030\002 \001(\003\022\013\n\003en"
    "d\030\003 \001(\003\022\014\n\004step\030\004 \001(\003\022\030\n\020environment_dat"
    "a\030\005 \001(\014\022\030\n\020environment_size\030\006 \001(\004\022\025\n\rfun"
    "ction_name\030\007 \001(\t\022\017\n\007ir_data\030\010 \001(\014\022\021\n\tir_"
    "format\030\t \001(\t\"\357\001\n\014TaskResponse\022\017\n\007task_id"
    "\030\001 \001(\003\022\017\n\007success\030\002 \001(\010\022\023\n\013result_data\030\003"
    " \001(\014\022\023\n\013result_size\030\004 \001(\004\022\025\n\rerror_messa"
    "ge\030\005 \001(\t\022C\n\021iteration_outputs\030\006 \003(\0132(.ta"
    "sk.TaskResponse.IterationOutputsEntry\0327\n"
    "\025IterationOutputsEntry\022\013\n\003key\030\001 \001(\003\022\r\n\005v"
    "alue\030\002 \001(\014:\0028\0012C\n\013TaskService\0224\n\013Execute"
    "Task\022\021.task.TaskRequest\032\022.task.TaskRespo"
    "nseb\006proto3"
};
static ::absl::once_flag descriptor_table_task_5fservice_2eproto_once;
PROTOBUF_CONSTINIT const ::_pbi::DescriptorTable descriptor_table_task_5fservice_2eproto = {
    false,
    false,
    531,
    descriptor_table_protodef_task_5fservice_2eproto,
    "task_service.proto",
    &descriptor_table_task_5fservice_2eproto_once,
    nullptr,
    0,
    3,
    schemas,
    file_default_instances,
    TableStruct_task_5fservice_2eproto::offsets,
    file_level_enum_descriptors_task_5fservice_2eproto,
    file_level_service_descriptors_task_5fservice_2eproto,
};
namespace task {
// ===================================================================

class TaskRequest::_Internal {
 public:
};

TaskRequest::TaskRequest(::google::protobuf::Arena* arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, _class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:task.TaskRequest)
}
inline PROTOBUF_NDEBUG_INLINE TaskRequest::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility, ::google::protobuf::Arena* arena,
    const Impl_& from, const ::task::TaskRequest& from_msg)
      : environment_data_(arena, from.environment_data_),
        function_name_(arena, from.function_name_),
        ir_data_(arena, from.ir_data_),
        ir_format_(arena, from.ir_format_),
        _cached_size_{0} {}

TaskRequest::TaskRequest(
    ::google::protobuf::Arena* arena,
    const TaskRequest& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, _class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  TaskRequest* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_, from);
  ::memcpy(reinterpret_cast<char *>(&_impl_) +
               offsetof(Impl_, task_id_),
           reinterpret_cast<const char *>(&from._impl_) +
               offsetof(Impl_, task_id_),
           offsetof(Impl_, environment_size_) -
               offsetof(Impl_, task_id_) +
               sizeof(Impl_::environment_size_));

  // @@protoc_insertion_point(copy_constructor:task.TaskRequest)
}
inline PROTOBUF_NDEBUG_INLINE TaskRequest::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena)
      : environment_data_(arena),
        function_name_(arena),
        ir_data_(arena),
        ir_format_(arena),
        _cached_size_{0} {}

inline void TaskRequest::SharedCtor(::_pb::Arena* arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  ::memset(reinterpret_cast<char *>(&_impl_) +
               offsetof(Impl_, task_id_),
           0,
           offsetof(Impl_, environment_size_) -
               offsetof(Impl_, task_id_) +
               sizeof(Impl_::environment_size_));
}
TaskRequest::~TaskRequest() {
  // @@protoc_insertion_point(destructor:task.TaskRequest)
  SharedDtor(*this);
}
inline void TaskRequest::SharedDtor(MessageLite& self) {
  TaskRequest& this_ = static_cast<TaskRequest&>(self);
  this_._internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  ABSL_DCHECK(this_.GetArena() == nullptr);
  this_._impl_.environment_data_.Destroy();
  this_._impl_.function_name_.Destroy();
  this_._impl_.ir_data_.Destroy();
  this_._impl_.ir_format_.Destroy();
  this_._impl_.~Impl_();
}

inline void* TaskRequest::PlacementNew_(const void*, void* mem,
                                        ::google::protobuf::Arena* arena) {
  return ::new (mem) TaskRequest(arena);
}
constexpr auto TaskRequest::InternalNewImpl_() {
  return ::google::protobuf::internal::MessageCreator::CopyInit(sizeof(TaskRequest),
                                            alignof(TaskRequest));
}
PROTOBUF_CONSTINIT
PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::google::protobuf::internal::ClassDataFull TaskRequest::_class_data_ = {
    ::google::protobuf::internal::ClassData{
        &_TaskRequest_default_instance_._instance,
        &_table_.header,
        nullptr,  // OnDemandRegisterArenaDtor
        nullptr,  // IsInitialized
        &TaskRequest::MergeImpl,
        ::google::protobuf::Message::GetNewImpl<TaskRequest>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
        &TaskRequest::SharedDtor,
        ::google::protobuf::Message::GetClearImpl<TaskRequest>(), &TaskRequest::ByteSizeLong,
            &TaskRequest::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
        PROTOBUF_FIELD_OFFSET(TaskRequest, _impl_._cached_size_),
        false,
    },
    &TaskRequest::kDescriptorMethods,
    &descriptor_table_task_5fservice_2eproto,
    nullptr,  // tracker
};
const ::google::protobuf::internal::ClassData* TaskRequest::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(_class_data_.tc_table);
  return _class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<4, 9, 0, 55, 2> TaskRequest::_table_ = {
  {
    0,  // no _has_bits_
    0, // no _extensions_
    9, 120,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294966784,  // skipmap
    offsetof(decltype(_table_), field_entries),
    9,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    _class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::task::TaskRequest>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    {::_pbi::TcParser::MiniParse, {}},
    // int64 task_id = 1;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint64_t, offsetof(TaskRequest, _impl_.task_id_), 63>(),
     {8, 63, 0, PROTOBUF_FIELD_OFFSET(TaskRequest, _impl_.task_id_)}},
    // int64 start = 2;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint64_t, offsetof(TaskRequest, _impl_.start_), 63>(),
     {16, 63, 0, PROTOBUF_FIELD_OFFSET(TaskRequest, _impl_.start_)}},
    // int64 end = 3;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint64_t, offsetof(TaskRequest, _impl_.end_), 63>(),
     {24, 63, 0, PROTOBUF_FIELD_OFFSET(TaskRequest, _impl_.end_)}},
    // int64 step = 4;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint64_t, offsetof(TaskRequest, _impl_.step_), 63>(),
     {32, 63, 0, PROTOBUF_FIELD_OFFSET(TaskRequest, _impl_.step_)}},
    // bytes environment_data = 5;
    {::_pbi::TcParser::FastBS1,
     {42, 63, 0, PROTOBUF_FIELD_OFFSET(TaskRequest, _impl_.environment_data_)}},
    // uint64 environment_size = 6;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint64_t, offsetof(TaskRequest, _impl_.environment_size_), 63>(),
     {48, 63, 0, PROTOBUF_FIELD_OFFSET(TaskRequest, _impl_.environment_size_)}},
    // string function_name = 7;
    {::_pbi::TcParser::FastUS1,
     {58, 63, 0, PROTOBUF_FIELD_OFFSET(TaskRequest, _impl_.function_name_)}},
    // bytes ir_data = 8;
    {::_pbi::TcParser::FastBS1,
     {66, 63, 0, PROTOBUF_FIELD_OFFSET(TaskRequest, _impl_.ir_data_)}},
    // string ir_format = 9;
    {::_pbi::TcParser::FastUS1,
     {74, 63, 0, PROTOBUF_FIELD_OFFSET(TaskRequest, _impl_.ir_format_)}},
    {::_pbi::TcParser::MiniParse, {}},
    {::_pbi::TcParser::MiniParse, {}},
    {::_pbi::TcParser::MiniParse, {}},
    {::_pbi::TcParser::MiniParse, {}},
    {::_pbi::TcParser::MiniParse, {}},
    {::_pbi::TcParser::MiniParse, {}},
  }}, {{
    65535, 65535
  }}, {{
    // int64 task_id = 1;
    {PROTOBUF_FIELD_OFFSET(TaskRequest, _impl_.task_id_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kInt64)},
    // int64 start = 2;
    {PROTOBUF_FIELD_OFFSET(TaskRequest, _impl_.start_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kInt64)},
    // int64 end = 3;
    {PROTOBUF_FIELD_OFFSET(TaskRequest, _impl_.end_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kInt64)},
    // int64 step = 4;
    {PROTOBUF_FIELD_OFFSET(TaskRequest, _impl_.step_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kInt64)},
    // bytes environment_data = 5;
    {PROTOBUF_FIELD_OFFSET(TaskRequest, _impl_.environment_data_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kBytes | ::_fl::kRepAString)},
    // uint64 environment_size = 6;
    {PROTOBUF_FIELD_OFFSET(TaskRequest, _impl_.environment_size_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kUInt64)},
    // string function_name = 7;
    {PROTOBUF_FIELD_OFFSET(TaskRequest, _impl_.function_name_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kUtf8String | ::_fl::kRepAString)},
    // bytes ir_data = 8;
    {PROTOBUF_FIELD_OFFSET(TaskRequest, _impl_.ir_data_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kBytes | ::_fl::kRepAString)},
    // string ir_format = 9;
    {PROTOBUF_FIELD_OFFSET(TaskRequest, _impl_.ir_format_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kUtf8String | ::_fl::kRepAString)},
  }},
  // no aux_entries
  {{
    "\20\0\0\0\0\0\0\15\0\11\0\0\0\0\0\0"
    "task.TaskRequest"
    "function_name"
    "ir_format"
  }},
};

PROTOBUF_NOINLINE void TaskRequest::Clear() {
// @@protoc_insertion_point(message_clear_start:task.TaskRequest)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.environment_data_.ClearToEmpty();
  _impl_.function_name_.ClearToEmpty();
  _impl_.ir_data_.ClearToEmpty();
  _impl_.ir_format_.ClearToEmpty();
  ::memset(&_impl_.task_id_, 0, static_cast<::size_t>(
      reinterpret_cast<char*>(&_impl_.environment_size_) -
      reinterpret_cast<char*>(&_impl_.task_id_)) + sizeof(_impl_.environment_size_));
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::uint8_t* TaskRequest::_InternalSerialize(
            const MessageLite& base, ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) {
          const TaskRequest& this_ = static_cast<const TaskRequest&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::uint8_t* TaskRequest::_InternalSerialize(
            ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) const {
          const TaskRequest& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(serialize_to_array_start:task.TaskRequest)
          ::uint32_t cached_has_bits = 0;
          (void)cached_has_bits;

          // int64 task_id = 1;
          if (this_._internal_task_id() != 0) {
            target = ::google::protobuf::internal::WireFormatLite::
                WriteInt64ToArrayWithField<1>(
                    stream, this_._internal_task_id(), target);
          }

          // int64 start = 2;
          if (this_._internal_start() != 0) {
            target = ::google::protobuf::internal::WireFormatLite::
                WriteInt64ToArrayWithField<2>(
                    stream, this_._internal_start(), target);
          }

          // int64 end = 3;
          if (this_._internal_end() != 0) {
            target = ::google::protobuf::internal::WireFormatLite::
                WriteInt64ToArrayWithField<3>(
                    stream, this_._internal_end(), target);
          }

          // int64 step = 4;
          if (this_._internal_step() != 0) {
            target = ::google::protobuf::internal::WireFormatLite::
                WriteInt64ToArrayWithField<4>(
                    stream, this_._internal_step(), target);
          }

          // bytes environment_data = 5;
          if (!this_._internal_environment_data().empty()) {
            const std::string& _s = this_._internal_environment_data();
            target = stream->WriteBytesMaybeAliased(5, _s, target);
          }

          // uint64 environment_size = 6;
          if (this_._internal_environment_size() != 0) {
            target = stream->EnsureSpace(target);
            target = ::_pbi::WireFormatLite::WriteUInt64ToArray(
                6, this_._internal_environment_size(), target);
          }

          // string function_name = 7;
          if (!this_._internal_function_name().empty()) {
            const std::string& _s = this_._internal_function_name();
            ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
                _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "task.TaskRequest.function_name");
            target = stream->WriteStringMaybeAliased(7, _s, target);
          }

          // bytes ir_data = 8;
          if (!this_._internal_ir_data().empty()) {
            const std::string& _s = this_._internal_ir_data();
            target = stream->WriteBytesMaybeAliased(8, _s, target);
          }

          // string ir_format = 9;
          if (!this_._internal_ir_format().empty()) {
            const std::string& _s = this_._internal_ir_format();
            ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
                _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "task.TaskRequest.ir_format");
            target = stream->WriteStringMaybeAliased(9, _s, target);
          }

          if (PROTOBUF_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
            target =
                ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
                    this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
          }
          // @@protoc_insertion_point(serialize_to_array_end:task.TaskRequest)
          return target;
        }

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::size_t TaskRequest::ByteSizeLong(const MessageLite& base) {
          const TaskRequest& this_ = static_cast<const TaskRequest&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::size_t TaskRequest::ByteSizeLong() const {
          const TaskRequest& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(message_byte_size_start:task.TaskRequest)
          ::size_t total_size = 0;

          ::uint32_t cached_has_bits = 0;
          // Prevent compiler warnings about cached_has_bits being unused
          (void)cached_has_bits;

          ::_pbi::Prefetch5LinesFrom7Lines(&this_);
           {
            // bytes environment_data = 5;
            if (!this_._internal_environment_data().empty()) {
              total_size += 1 + ::google::protobuf::internal::WireFormatLite::BytesSize(
                                              this_._internal_environment_data());
            }
            // string function_name = 7;
            if (!this_._internal_function_name().empty()) {
              total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                              this_._internal_function_name());
            }
            // bytes ir_data = 8;
            if (!this_._internal_ir_data().empty()) {
              total_size += 1 + ::google::protobuf::internal::WireFormatLite::BytesSize(
                                              this_._internal_ir_data());
            }
            // string ir_format = 9;
            if (!this_._internal_ir_format().empty()) {
              total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                              this_._internal_ir_format());
            }
            // int64 task_id = 1;
            if (this_._internal_task_id() != 0) {
              total_size += ::_pbi::WireFormatLite::Int64SizePlusOne(
                  this_._internal_task_id());
            }
            // int64 start = 2;
            if (this_._internal_start() != 0) {
              total_size += ::_pbi::WireFormatLite::Int64SizePlusOne(
                  this_._internal_start());
            }
            // int64 end = 3;
            if (this_._internal_end() != 0) {
              total_size += ::_pbi::WireFormatLite::Int64SizePlusOne(
                  this_._internal_end());
            }
            // int64 step = 4;
            if (this_._internal_step() != 0) {
              total_size += ::_pbi::WireFormatLite::Int64SizePlusOne(
                  this_._internal_step());
            }
            // uint64 environment_size = 6;
            if (this_._internal_environment_size() != 0) {
              total_size += ::_pbi::WireFormatLite::UInt64SizePlusOne(
                  this_._internal_environment_size());
            }
          }
          return this_.MaybeComputeUnknownFieldsSize(total_size,
                                                     &this_._impl_._cached_size_);
        }

void TaskRequest::MergeImpl(::google::protobuf::MessageLite& to_msg, const ::google::protobuf::MessageLite& from_msg) {
  auto* const _this = static_cast<TaskRequest*>(&to_msg);
  auto& from = static_cast<const TaskRequest&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:task.TaskRequest)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (!from._internal_environment_data().empty()) {
    _this->_internal_set_environment_data(from._internal_environment_data());
  }
  if (!from._internal_function_name().empty()) {
    _this->_internal_set_function_name(from._internal_function_name());
  }
  if (!from._internal_ir_data().empty()) {
    _this->_internal_set_ir_data(from._internal_ir_data());
  }
  if (!from._internal_ir_format().empty()) {
    _this->_internal_set_ir_format(from._internal_ir_format());
  }
  if (from._internal_task_id() != 0) {
    _this->_impl_.task_id_ = from._impl_.task_id_;
  }
  if (from._internal_start() != 0) {
    _this->_impl_.start_ = from._impl_.start_;
  }
  if (from._internal_end() != 0) {
    _this->_impl_.end_ = from._impl_.end_;
  }
  if (from._internal_step() != 0) {
    _this->_impl_.step_ = from._impl_.step_;
  }
  if (from._internal_environment_size() != 0) {
    _this->_impl_.environment_size_ = from._impl_.environment_size_;
  }
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void TaskRequest::CopyFrom(const TaskRequest& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:task.TaskRequest)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void TaskRequest::InternalSwap(TaskRequest* PROTOBUF_RESTRICT other) {
  using std::swap;
  auto* arena = GetArena();
  ABSL_DCHECK_EQ(arena, other->GetArena());
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.environment_data_, &other->_impl_.environment_data_, arena);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.function_name_, &other->_impl_.function_name_, arena);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.ir_data_, &other->_impl_.ir_data_, arena);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.ir_format_, &other->_impl_.ir_format_, arena);
  ::google::protobuf::internal::memswap<
      PROTOBUF_FIELD_OFFSET(TaskRequest, _impl_.environment_size_)
      + sizeof(TaskRequest::_impl_.environment_size_)
      - PROTOBUF_FIELD_OFFSET(TaskRequest, _impl_.task_id_)>(
          reinterpret_cast<char*>(&_impl_.task_id_),
          reinterpret_cast<char*>(&other->_impl_.task_id_));
}

::google::protobuf::Metadata TaskRequest::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// ===================================================================

#if defined(PROTOBUF_CUSTOM_VTABLE)
              TaskResponse_IterationOutputsEntry_DoNotUse::TaskResponse_IterationOutputsEntry_DoNotUse() : SuperType(_class_data_.base()) {}
              TaskResponse_IterationOutputsEntry_DoNotUse::TaskResponse_IterationOutputsEntry_DoNotUse(::google::protobuf::Arena* arena)
                  : SuperType(arena, _class_data_.base()) {}
#else   // PROTOBUF_CUSTOM_VTABLE
              TaskResponse_IterationOutputsEntry_DoNotUse::TaskResponse_IterationOutputsEntry_DoNotUse() : SuperType() {}
              TaskResponse_IterationOutputsEntry_DoNotUse::TaskResponse_IterationOutputsEntry_DoNotUse(::google::protobuf::Arena* arena) : SuperType(arena) {}
#endif  // PROTOBUF_CUSTOM_VTABLE
              inline void* TaskResponse_IterationOutputsEntry_DoNotUse::PlacementNew_(const void*, void* mem,
                                                      ::google::protobuf::Arena* arena) {
                return ::new (mem) TaskResponse_IterationOutputsEntry_DoNotUse(arena);
              }
              constexpr auto TaskResponse_IterationOutputsEntry_DoNotUse::InternalNewImpl_() {
                return ::google::protobuf::internal::MessageCreator::CopyInit(sizeof(TaskResponse_IterationOutputsEntry_DoNotUse),
                                                          alignof(TaskResponse_IterationOutputsEntry_DoNotUse));
              }
              PROTOBUF_CONSTINIT
              PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
              const ::google::protobuf::internal::ClassDataFull TaskResponse_IterationOutputsEntry_DoNotUse::_class_data_ = {
                  ::google::protobuf::internal::ClassData{
                      &_TaskResponse_IterationOutputsEntry_DoNotUse_default_instance_._instance,
                      &_table_.header,
                      nullptr,  // OnDemandRegisterArenaDtor
                      nullptr,  // IsInitialized
                      &TaskResponse_IterationOutputsEntry_DoNotUse::MergeImpl,
                      ::google::protobuf::Message::GetNewImpl<TaskResponse_IterationOutputsEntry_DoNotUse>(),
              #if defined(PROTOBUF_CUSTOM_VTABLE)
                      &TaskResponse_IterationOutputsEntry_DoNotUse::SharedDtor,
                      static_cast<void (::google::protobuf::MessageLite::*)()>(
                          &TaskResponse_IterationOutputsEntry_DoNotUse::ClearImpl),
                          ::google::protobuf::Message::ByteSizeLongImpl, ::google::protobuf::Message::_InternalSerializeImpl
                          ,
              #endif  // PROTOBUF_CUSTOM_VTABLE
                      PROTOBUF_FIELD_OFFSET(TaskResponse_IterationOutputsEntry_DoNotUse, _impl_._cached_size_),
                      false,
                  },
                  &TaskResponse_IterationOutputsEntry_DoNotUse::kDescriptorMethods,
                  &descriptor_table_task_5fservice_2eproto,
                  nullptr,  // tracker
              };
              const ::google::protobuf::internal::ClassData* TaskResponse_IterationOutputsEntry_DoNotUse::GetClassData() const {
                ::google::protobuf::internal::PrefetchToLocalCache(&_class_data_);
                ::google::protobuf::internal::PrefetchToLocalCache(_class_data_.tc_table);
                return _class_data_.base();
              }
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<1, 2, 0, 0, 2> TaskResponse_IterationOutputsEntry_DoNotUse::_table_ = {
  {
    PROTOBUF_FIELD_OFFSET(TaskResponse_IterationOutputsEntry_DoNotUse, _impl_._has_bits_),
    0, // no _extensions_
    2, 8,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967292,  // skipmap
    offsetof(decltype(_table_), field_entries),
    2,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    _class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::DiscardEverythingFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::task::TaskResponse_IterationOutputsEntry_DoNotUse>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    // bytes value = 2;
    {::_pbi::TcParser::FastBS1,
     {18, 63, 0, PROTOBUF_FIELD_OFFSET(TaskResponse_IterationOutputsEntry_DoNotUse, _impl_.value_)}},
    // int64 key = 1;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint64_t, offsetof(TaskResponse_IterationOutputsEntry_DoNotUse, _impl_.key_), 63>(),
     {8, 63, 0, PROTOBUF_FIELD_OFFSET(TaskResponse_IterationOutputsEntry_DoNotUse, _impl_.key_)}},
  }}, {{
    65535, 65535
  }}, {{
    // int64 key = 1;
    {PROTOBUF_FIELD_OFFSET(TaskResponse_IterationOutputsEntry_DoNotUse, _impl_.key_), -1, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kInt64)},
    // bytes value = 2;
    {PROTOBUF_FIELD_OFFSET(TaskResponse_IterationOutputsEntry_DoNotUse, _impl_.value_), -1, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kBytes | ::_fl::kRepAString)},
  }},
  // no aux_entries
  {{
  }},
};

// ===================================================================

class TaskResponse::_Internal {
 public:
};

TaskResponse::TaskResponse(::google::protobuf::Arena* arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, _class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:task.TaskResponse)
}
inline PROTOBUF_NDEBUG_INLINE TaskResponse::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility, ::google::protobuf::Arena* arena,
    const Impl_& from, const ::task::TaskResponse& from_msg)
      : iteration_outputs_{visibility, arena, from.iteration_outputs_},
        result_data_(arena, from.result_data_),
        error_message_(arena, from.error_message_),
        _cached_size_{0} {}

TaskResponse::TaskResponse(
    ::google::protobuf::Arena* arena,
    const TaskResponse& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, _class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  TaskResponse* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_, from);
  ::memcpy(reinterpret_cast<char *>(&_impl_) +
               offsetof(Impl_, task_id_),
           reinterpret_cast<const char *>(&from._impl_) +
               offsetof(Impl_, task_id_),
           offsetof(Impl_, success_) -
               offsetof(Impl_, task_id_) +
               sizeof(Impl_::success_));

  // @@protoc_insertion_point(copy_constructor:task.TaskResponse)
}
inline PROTOBUF_NDEBUG_INLINE TaskResponse::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena)
      : iteration_outputs_{visibility, arena},
        result_data_(arena),
        error_message_(arena),
        _cached_size_{0} {}

inline void TaskResponse::SharedCtor(::_pb::Arena* arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  ::memset(reinterpret_cast<char *>(&_impl_) +
               offsetof(Impl_, task_id_),
           0,
           offsetof(Impl_, success_) -
               offsetof(Impl_, task_id_) +
               sizeof(Impl_::success_));
}
TaskResponse::~TaskResponse() {
  // @@protoc_insertion_point(destructor:task.TaskResponse)
  SharedDtor(*this);
}
inline void TaskResponse::SharedDtor(MessageLite& self) {
  TaskResponse& this_ = static_cast<TaskResponse&>(self);
  this_._internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  ABSL_DCHECK(this_.GetArena() == nullptr);
  this_._impl_.result_data_.Destroy();
  this_._impl_.error_message_.Destroy();
  this_._impl_.~Impl_();
}

inline void* TaskResponse::PlacementNew_(const void*, void* mem,
                                        ::google::protobuf::Arena* arena) {
  return ::new (mem) TaskResponse(arena);
}
constexpr auto TaskResponse::InternalNewImpl_() {
  constexpr auto arena_bits = ::google::protobuf::internal::EncodePlacementArenaOffsets({
      PROTOBUF_FIELD_OFFSET(TaskResponse, _impl_.iteration_outputs_) +
          decltype(TaskResponse::_impl_.iteration_outputs_)::
              InternalGetArenaOffset(
                  ::google::protobuf::Message::internal_visibility()),
      PROTOBUF_FIELD_OFFSET(TaskResponse, _impl_.iteration_outputs_) +
          decltype(TaskResponse::_impl_.iteration_outputs_)::
              InternalGetArenaOffsetAlt(
                  ::google::protobuf::Message::internal_visibility()),
  });
  if (arena_bits.has_value()) {
    return ::google::protobuf::internal::MessageCreator::CopyInit(
        sizeof(TaskResponse), alignof(TaskResponse), *arena_bits);
  } else {
    return ::google::protobuf::internal::MessageCreator(&TaskResponse::PlacementNew_,
                                 sizeof(TaskResponse),
                                 alignof(TaskResponse));
  }
}
PROTOBUF_CONSTINIT
PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::google::protobuf::internal::ClassDataFull TaskResponse::_class_data_ = {
    ::google::protobuf::internal::ClassData{
        &_TaskResponse_default_instance_._instance,
        &_table_.header,
        nullptr,  // OnDemandRegisterArenaDtor
        nullptr,  // IsInitialized
        &TaskResponse::MergeImpl,
        ::google::protobuf::Message::GetNewImpl<TaskResponse>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
        &TaskResponse::SharedDtor,
        ::google::protobuf::Message::GetClearImpl<TaskResponse>(), &TaskResponse::ByteSizeLong,
            &TaskResponse::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
        PROTOBUF_FIELD_OFFSET(TaskResponse, _impl_._cached_size_),
        false,
    },
    &TaskResponse::kDescriptorMethods,
    &descriptor_table_task_5fservice_2eproto,
    nullptr,  // tracker
};
const ::google::protobuf::internal::ClassData* TaskResponse::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(_class_data_.tc_table);
  return _class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<3, 6, 1, 39, 2> TaskResponse::_table_ = {
  {
    0,  // no _has_bits_
    0, // no _extensions_
    6, 56,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967232,  // skipmap
    offsetof(decltype(_table_), field_entries),
    6,  // num_field_entries
    1,  // num_aux_entries
    offsetof(decltype(_table_), aux_entries),
    _class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::task::TaskResponse>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    {::_pbi::TcParser::MiniParse, {}},
    // int64 task_id = 1;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint64_t, offsetof(TaskResponse, _impl_.task_id_), 63>(),
     {8, 63, 0, PROTOBUF_FIELD_OFFSET(TaskResponse, _impl_.task_id_)}},
    // bool success = 2;
    {::_pbi::TcParser::SingularVarintNoZag1<bool, offsetof(TaskResponse, _impl_.success_), 63>(),
     {16, 63, 0, PROTOBUF_FIELD_OFFSET(TaskResponse, _impl_.success_)}},
    // bytes result_data = 3;
    {::_pbi::TcParser::FastBS1,
     {26, 63, 0, PROTOBUF_FIELD_OFFSET(TaskResponse, _impl_.result_data_)}},
    // uint64 result_size = 4;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint64_t, offsetof(TaskResponse, _impl_.result_size_), 63>(),
     {32, 63, 0, PROTOBUF_FIELD_OFFSET(TaskResponse, _impl_.result_size_)}},
    // string error_message = 5;
    {::_pbi::TcParser::FastUS1,
     {42, 63, 0, PROTOBUF_FIELD_OFFSET(TaskResponse, _impl_.error_message_)}},
    {::_pbi::TcParser::MiniParse, {}},
    {::_pbi::TcParser::MiniParse, {}},
  }}, {{
    65535, 65535
  }}, {{
    // int64 task_id = 1;
    {PROTOBUF_FIELD_OFFSET(TaskResponse, _impl_.task_id_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kInt64)},
    // bool success = 2;
    {PROTOBUF_FIELD_OFFSET(TaskResponse, _impl_.success_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kBool)},
    // bytes result_data = 3;
    {PROTOBUF_FIELD_OFFSET(TaskResponse, _impl_.result_data_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kBytes | ::_fl::kRepAString)},
    // uint64 result_size = 4;
    {PROTOBUF_FIELD_OFFSET(TaskResponse, _impl_.result_size_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kUInt64)},
    // string error_message = 5;
    {PROTOBUF_FIELD_OFFSET(TaskResponse, _impl_.error_message_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kUtf8String | ::_fl::kRepAString)},
    // map<int64, bytes> iteration_outputs = 6;
    {PROTOBUF_FIELD_OFFSET(TaskResponse, _impl_.iteration_outputs_), 0, 0,
    (0 | ::_fl::kFcRepeated | ::_fl::kMap)},
  }}, {{
    {::_pbi::TcParser::GetMapAuxInfo<
        decltype(TaskResponse()._impl_.iteration_outputs_)>(
        0, 0, 0, 3,
        12)},
  }}, {{
    "\21\0\0\0\0\15\0\0"
    "task.TaskResponse"
    "error_message"
  }},
};

PROTOBUF_NOINLINE void TaskResponse::Clear() {
// @@protoc_insertion_point(message_clear_start:task.TaskResponse)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.iteration_outputs_.Clear();
  _impl_.result_data_.ClearToEmpty();
  _impl_.error_message_.ClearToEmpty();
  ::memset(&_impl_.task_id_, 0, static_cast<::size_t>(
      reinterpret_cast<char*>(&_impl_.success_) -
      reinterpret_cast<char*>(&_impl_.task_id_)) + sizeof(_impl_.success_));
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::uint8_t* TaskResponse::_InternalSerialize(
            const MessageLite& base, ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) {
          const TaskResponse& this_ = static_cast<const TaskResponse&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::uint8_t* TaskResponse::_InternalSerialize(
            ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) const {
          const TaskResponse& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(serialize_to_array_start:task.TaskResponse)
          ::uint32_t cached_has_bits = 0;
          (void)cached_has_bits;

          // int64 task_id = 1;
          if (this_._internal_task_id() != 0) {
            target = ::google::protobuf::internal::WireFormatLite::
                WriteInt64ToArrayWithField<1>(
                    stream, this_._internal_task_id(), target);
          }

          // bool success = 2;
          if (this_._internal_success() != 0) {
            target = stream->EnsureSpace(target);
            target = ::_pbi::WireFormatLite::WriteBoolToArray(
                2, this_._internal_success(), target);
          }

          // bytes result_data = 3;
          if (!this_._internal_result_data().empty()) {
            const std::string& _s = this_._internal_result_data();
            target = stream->WriteBytesMaybeAliased(3, _s, target);
          }

          // uint64 result_size = 4;
          if (this_._internal_result_size() != 0) {
            target = stream->EnsureSpace(target);
            target = ::_pbi::WireFormatLite::WriteUInt64ToArray(
                4, this_._internal_result_size(), target);
          }

          // string error_message = 5;
          if (!this_._internal_error_message().empty()) {
            const std::string& _s = this_._internal_error_message();
            ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
                _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "task.TaskResponse.error_message");
            target = stream->WriteStringMaybeAliased(5, _s, target);
          }

          // map<int64, bytes> iteration_outputs = 6;
          if (!this_._internal_iteration_outputs().empty()) {
            using MapType = ::google::protobuf::Map<::int64_t, std::string>;
            using WireHelper = _pbi::MapEntryFuncs<::int64_t, std::string,
                                           _pbi::WireFormatLite::TYPE_INT64,
                                           _pbi::WireFormatLite::TYPE_BYTES>;
            const auto& field = this_._internal_iteration_outputs();

            if (stream->IsSerializationDeterministic() && field.size() > 1) {
              for (const auto& entry : ::google::protobuf::internal::MapSorterFlat<MapType>(field)) {
                target = WireHelper::InternalSerialize(
                    6, entry.first, entry.second, target, stream);
              }
            } else {
              for (const auto& entry : field) {
                target = WireHelper::InternalSerialize(
                    6, entry.first, entry.second, target, stream);
              }
            }
          }

          if (PROTOBUF_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
            target =
                ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
                    this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
          }
          // @@protoc_insertion_point(serialize_to_array_end:task.TaskResponse)
          return target;
        }

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::size_t TaskResponse::ByteSizeLong(const MessageLite& base) {
          const TaskResponse& this_ = static_cast<const TaskResponse&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::size_t TaskResponse::ByteSizeLong() const {
          const TaskResponse& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(message_byte_size_start:task.TaskResponse)
          ::size_t total_size = 0;

          ::uint32_t cached_has_bits = 0;
          // Prevent compiler warnings about cached_has_bits being unused
          (void)cached_has_bits;

          ::_pbi::Prefetch5LinesFrom7Lines(&this_);
           {
            // map<int64, bytes> iteration_outputs = 6;
            {
              total_size +=
                  1 * ::google::protobuf::internal::FromIntSize(this_._internal_iteration_outputs_size());
              for (const auto& entry : this_._internal_iteration_outputs()) {
                total_size += _pbi::MapEntryFuncs<::int64_t, std::string,
                                               _pbi::WireFormatLite::TYPE_INT64,
                                               _pbi::WireFormatLite::TYPE_BYTES>::ByteSizeLong(entry.first, entry.second);
              }
            }
          }
           {
            // bytes result_data = 3;
            if (!this_._internal_result_data().empty()) {
              total_size += 1 + ::google::protobuf::internal::WireFormatLite::BytesSize(
                                              this_._internal_result_data());
            }
            // string error_message = 5;
            if (!this_._internal_error_message().empty()) {
              total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                              this_._internal_error_message());
            }
            // int64 task_id = 1;
            if (this_._internal_task_id() != 0) {
              total_size += ::_pbi::WireFormatLite::Int64SizePlusOne(
                  this_._internal_task_id());
            }
            // uint64 result_size = 4;
            if (this_._internal_result_size() != 0) {
              total_size += ::_pbi::WireFormatLite::UInt64SizePlusOne(
                  this_._internal_result_size());
            }
            // bool success = 2;
            if (this_._internal_success() != 0) {
              total_size += 2;
            }
          }
          return this_.MaybeComputeUnknownFieldsSize(total_size,
                                                     &this_._impl_._cached_size_);
        }

void TaskResponse::MergeImpl(::google::protobuf::MessageLite& to_msg, const ::google::protobuf::MessageLite& from_msg) {
  auto* const _this = static_cast<TaskResponse*>(&to_msg);
  auto& from = static_cast<const TaskResponse&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:task.TaskResponse)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  _this->_impl_.iteration_outputs_.MergeFrom(from._impl_.iteration_outputs_);
  if (!from._internal_result_data().empty()) {
    _this->_internal_set_result_data(from._internal_result_data());
  }
  if (!from._internal_error_message().empty()) {
    _this->_internal_set_error_message(from._internal_error_message());
  }
  if (from._internal_task_id() != 0) {
    _this->_impl_.task_id_ = from._impl_.task_id_;
  }
  if (from._internal_result_size() != 0) {
    _this->_impl_.result_size_ = from._impl_.result_size_;
  }
  if (from._internal_success() != 0) {
    _this->_impl_.success_ = from._impl_.success_;
  }
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void TaskResponse::CopyFrom(const TaskResponse& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:task.TaskResponse)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void TaskResponse::InternalSwap(TaskResponse* PROTOBUF_RESTRICT other) {
  using std::swap;
  auto* arena = GetArena();
  ABSL_DCHECK_EQ(arena, other->GetArena());
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  _impl_.iteration_outputs_.InternalSwap(&other->_impl_.iteration_outputs_);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.result_data_, &other->_impl_.result_data_, arena);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.error_message_, &other->_impl_.error_message_, arena);
  ::google::protobuf::internal::memswap<
      PROTOBUF_FIELD_OFFSET(TaskResponse, _impl_.success_)
      + sizeof(TaskResponse::_impl_.success_)
      - PROTOBUF_FIELD_OFFSET(TaskResponse, _impl_.task_id_)>(
          reinterpret_cast<char*>(&_impl_.task_id_),
          reinterpret_cast<char*>(&other->_impl_.task_id_));
}

::google::protobuf::Metadata TaskResponse::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// @@protoc_insertion_point(namespace_scope)
}  // namespace task
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google
// @@protoc_insertion_point(global_scope)
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 static ::std::false_type
    _static_init2_ PROTOBUF_UNUSED =
        (::_pbi::AddDescriptors(&descriptor_table_task_5fservice_2eproto),
         ::std::false_type{});
#include "google/protobuf/port_undef.inc"
