// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: task_service.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_task_5fservice_2eproto
#define GOOGLE_PROTOBUF_INCLUDED_task_5fservice_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3021000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3021006 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata_lite.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/map.h>  // IWYU pragma: export
#include <google/protobuf/map_entry.h>
#include <google/protobuf/map_field_inl.h>
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_task_5fservice_2eproto
PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_task_5fservice_2eproto {
  static const uint32_t offsets[];
};
extern const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_task_5fservice_2eproto;
namespace task {
class TaskRequest;
struct TaskRequestDefaultTypeInternal;
extern TaskRequestDefaultTypeInternal _TaskRequest_default_instance_;
class TaskResponse;
struct TaskResponseDefaultTypeInternal;
extern TaskResponseDefaultTypeInternal _TaskResponse_default_instance_;
class TaskResponse_IterationOutputsEntry_DoNotUse;
struct TaskResponse_IterationOutputsEntry_DoNotUseDefaultTypeInternal;
extern TaskResponse_IterationOutputsEntry_DoNotUseDefaultTypeInternal _TaskResponse_IterationOutputsEntry_DoNotUse_default_instance_;
}  // namespace task
PROTOBUF_NAMESPACE_OPEN
template<> ::task::TaskRequest* Arena::CreateMaybeMessage<::task::TaskRequest>(Arena*);
template<> ::task::TaskResponse* Arena::CreateMaybeMessage<::task::TaskResponse>(Arena*);
template<> ::task::TaskResponse_IterationOutputsEntry_DoNotUse* Arena::CreateMaybeMessage<::task::TaskResponse_IterationOutputsEntry_DoNotUse>(Arena*);
PROTOBUF_NAMESPACE_CLOSE
namespace task {

// ===================================================================

class TaskRequest final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:task.TaskRequest) */ {
 public:
  inline TaskRequest() : TaskRequest(nullptr) {}
  ~TaskRequest() override;
  explicit PROTOBUF_CONSTEXPR TaskRequest(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  TaskRequest(const TaskRequest& from);
  TaskRequest(TaskRequest&& from) noexcept
    : TaskRequest() {
    *this = ::std::move(from);
  }

  inline TaskRequest& operator=(const TaskRequest& from) {
    CopyFrom(from);
    return *this;
  }
  inline TaskRequest& operator=(TaskRequest&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const TaskRequest& default_instance() {
    return *internal_default_instance();
  }
  static inline const TaskRequest* internal_default_instance() {
    return reinterpret_cast<const TaskRequest*>(
               &_TaskRequest_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(TaskRequest& a, TaskRequest& b) {
    a.Swap(&b);
  }
  inline void Swap(TaskRequest* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(TaskRequest* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  TaskRequest* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<TaskRequest>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const TaskRequest& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const TaskRequest& from) {
    TaskRequest::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(TaskRequest* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "task.TaskRequest";
  }
  protected:
  explicit TaskRequest(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kEnvironmentDataFieldNumber = 5,
    kFunctionNameFieldNumber = 7,
    kTaskIdFieldNumber = 1,
    kStartFieldNumber = 2,
    kEndFieldNumber = 3,
    kStepFieldNumber = 4,
    kEnvironmentSizeFieldNumber = 6,
  };
  // bytes environment_data = 5;
  void clear_environment_data();
  const std::string& environment_data() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_environment_data(ArgT0&& arg0, ArgT... args);
  std::string* mutable_environment_data();
  PROTOBUF_NODISCARD std::string* release_environment_data();
  void set_allocated_environment_data(std::string* environment_data);
  private:
  const std::string& _internal_environment_data() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_environment_data(const std::string& value);
  std::string* _internal_mutable_environment_data();
  public:

  // string function_name = 7;
  void clear_function_name();
  const std::string& function_name() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_function_name(ArgT0&& arg0, ArgT... args);
  std::string* mutable_function_name();
  PROTOBUF_NODISCARD std::string* release_function_name();
  void set_allocated_function_name(std::string* function_name);
  private:
  const std::string& _internal_function_name() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_function_name(const std::string& value);
  std::string* _internal_mutable_function_name();
  public:

  // int64 task_id = 1;
  void clear_task_id();
  int64_t task_id() const;
  void set_task_id(int64_t value);
  private:
  int64_t _internal_task_id() const;
  void _internal_set_task_id(int64_t value);
  public:

  // int64 start = 2;
  void clear_start();
  int64_t start() const;
  void set_start(int64_t value);
  private:
  int64_t _internal_start() const;
  void _internal_set_start(int64_t value);
  public:

  // int64 end = 3;
  void clear_end();
  int64_t end() const;
  void set_end(int64_t value);
  private:
  int64_t _internal_end() const;
  void _internal_set_end(int64_t value);
  public:

  // int64 step = 4;
  void clear_step();
  int64_t step() const;
  void set_step(int64_t value);
  private:
  int64_t _internal_step() const;
  void _internal_set_step(int64_t value);
  public:

  // uint64 environment_size = 6;
  void clear_environment_size();
  uint64_t environment_size() const;
  void set_environment_size(uint64_t value);
  private:
  uint64_t _internal_environment_size() const;
  void _internal_set_environment_size(uint64_t value);
  public:

  // @@protoc_insertion_point(class_scope:task.TaskRequest)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr environment_data_;
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr function_name_;
    int64_t task_id_;
    int64_t start_;
    int64_t end_;
    int64_t step_;
    uint64_t environment_size_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_task_5fservice_2eproto;
};
// -------------------------------------------------------------------

class TaskResponse_IterationOutputsEntry_DoNotUse : public ::PROTOBUF_NAMESPACE_ID::internal::MapEntry<TaskResponse_IterationOutputsEntry_DoNotUse, 
    int64_t, std::string,
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::TYPE_INT64,
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::TYPE_BYTES> {
public:
  typedef ::PROTOBUF_NAMESPACE_ID::internal::MapEntry<TaskResponse_IterationOutputsEntry_DoNotUse, 
    int64_t, std::string,
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::TYPE_INT64,
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::TYPE_BYTES> SuperType;
  TaskResponse_IterationOutputsEntry_DoNotUse();
  explicit PROTOBUF_CONSTEXPR TaskResponse_IterationOutputsEntry_DoNotUse(
      ::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);
  explicit TaskResponse_IterationOutputsEntry_DoNotUse(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  void MergeFrom(const TaskResponse_IterationOutputsEntry_DoNotUse& other);
  static const TaskResponse_IterationOutputsEntry_DoNotUse* internal_default_instance() { return reinterpret_cast<const TaskResponse_IterationOutputsEntry_DoNotUse*>(&_TaskResponse_IterationOutputsEntry_DoNotUse_default_instance_); }
  static bool ValidateKey(void*) { return true; }
  static bool ValidateValue(void*) { return true; }
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  friend struct ::TableStruct_task_5fservice_2eproto;
};

// -------------------------------------------------------------------

class TaskResponse final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:task.TaskResponse) */ {
 public:
  inline TaskResponse() : TaskResponse(nullptr) {}
  ~TaskResponse() override;
  explicit PROTOBUF_CONSTEXPR TaskResponse(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  TaskResponse(const TaskResponse& from);
  TaskResponse(TaskResponse&& from) noexcept
    : TaskResponse() {
    *this = ::std::move(from);
  }

  inline TaskResponse& operator=(const TaskResponse& from) {
    CopyFrom(from);
    return *this;
  }
  inline TaskResponse& operator=(TaskResponse&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const TaskResponse& default_instance() {
    return *internal_default_instance();
  }
  static inline const TaskResponse* internal_default_instance() {
    return reinterpret_cast<const TaskResponse*>(
               &_TaskResponse_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    2;

  friend void swap(TaskResponse& a, TaskResponse& b) {
    a.Swap(&b);
  }
  inline void Swap(TaskResponse* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(TaskResponse* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  TaskResponse* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<TaskResponse>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const TaskResponse& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const TaskResponse& from) {
    TaskResponse::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(TaskResponse* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "task.TaskResponse";
  }
  protected:
  explicit TaskResponse(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  private:
  static void ArenaDtor(void* object);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------


  // accessors -------------------------------------------------------

  enum : int {
    kIterationOutputsFieldNumber = 6,
    kResultDataFieldNumber = 3,
    kErrorMessageFieldNumber = 5,
    kTaskIdFieldNumber = 1,
    kResultSizeFieldNumber = 4,
    kSuccessFieldNumber = 2,
  };
  // map<int64, bytes> iteration_outputs = 6;
  int iteration_outputs_size() const;
  private:
  int _internal_iteration_outputs_size() const;
  public:
  void clear_iteration_outputs();
  private:
  const ::PROTOBUF_NAMESPACE_ID::Map< int64_t, std::string >&
      _internal_iteration_outputs() const;
  ::PROTOBUF_NAMESPACE_ID::Map< int64_t, std::string >*
      _internal_mutable_iteration_outputs();
  public:
  const ::PROTOBUF_NAMESPACE_ID::Map< int64_t, std::string >&
      iteration_outputs() const;
  ::PROTOBUF_NAMESPACE_ID::Map< int64_t, std::string >*
      mutable_iteration_outputs();

  // bytes result_data = 3;
  void clear_result_data();
  const std::string& result_data() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_result_data(ArgT0&& arg0, ArgT... args);
  std::string* mutable_result_data();
  PROTOBUF_NODISCARD std::string* release_result_data();
  void set_allocated_result_data(std::string* result_data);
  private:
  const std::string& _internal_result_data() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_result_data(const std::string& value);
  std::string* _internal_mutable_result_data();
  public:

  // string error_message = 5;
  void clear_error_message();
  const std::string& error_message() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_error_message(ArgT0&& arg0, ArgT... args);
  std::string* mutable_error_message();
  PROTOBUF_NODISCARD std::string* release_error_message();
  void set_allocated_error_message(std::string* error_message);
  private:
  const std::string& _internal_error_message() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_error_message(const std::string& value);
  std::string* _internal_mutable_error_message();
  public:

  // int64 task_id = 1;
  void clear_task_id();
  int64_t task_id() const;
  void set_task_id(int64_t value);
  private:
  int64_t _internal_task_id() const;
  void _internal_set_task_id(int64_t value);
  public:

  // uint64 result_size = 4;
  void clear_result_size();
  uint64_t result_size() const;
  void set_result_size(uint64_t value);
  private:
  uint64_t _internal_result_size() const;
  void _internal_set_result_size(uint64_t value);
  public:

  // bool success = 2;
  void clear_success();
  bool success() const;
  void set_success(bool value);
  private:
  bool _internal_success() const;
  void _internal_set_success(bool value);
  public:

  // @@protoc_insertion_point(class_scope:task.TaskResponse)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::PROTOBUF_NAMESPACE_ID::internal::MapField<
        TaskResponse_IterationOutputsEntry_DoNotUse,
        int64_t, std::string,
        ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::TYPE_INT64,
        ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::TYPE_BYTES> iteration_outputs_;
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr result_data_;
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr error_message_;
    int64_t task_id_;
    uint64_t result_size_;
    bool success_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_task_5fservice_2eproto;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// TaskRequest

// int64 task_id = 1;
inline void TaskRequest::clear_task_id() {
  _impl_.task_id_ = int64_t{0};
}
inline int64_t TaskRequest::_internal_task_id() const {
  return _impl_.task_id_;
}
inline int64_t TaskRequest::task_id() const {
  // @@protoc_insertion_point(field_get:task.TaskRequest.task_id)
  return _internal_task_id();
}
inline void TaskRequest::_internal_set_task_id(int64_t value) {
  
  _impl_.task_id_ = value;
}
inline void TaskRequest::set_task_id(int64_t value) {
  _internal_set_task_id(value);
  // @@protoc_insertion_point(field_set:task.TaskRequest.task_id)
}

// int64 start = 2;
inline void TaskRequest::clear_start() {
  _impl_.start_ = int64_t{0};
}
inline int64_t TaskRequest::_internal_start() const {
  return _impl_.start_;
}
inline int64_t TaskRequest::start() const {
  // @@protoc_insertion_point(field_get:task.TaskRequest.start)
  return _internal_start();
}
inline void TaskRequest::_internal_set_start(int64_t value) {
  
  _impl_.start_ = value;
}
inline void TaskRequest::set_start(int64_t value) {
  _internal_set_start(value);
  // @@protoc_insertion_point(field_set:task.TaskRequest.start)
}

// int64 end = 3;
inline void TaskRequest::clear_end() {
  _impl_.end_ = int64_t{0};
}
inline int64_t TaskRequest::_internal_end() const {
  return _impl_.end_;
}
inline int64_t TaskRequest::end() const {
  // @@protoc_insertion_point(field_get:task.TaskRequest.end)
  return _internal_end();
}
inline void TaskRequest::_internal_set_end(int64_t value) {
  
  _impl_.end_ = value;
}
inline void TaskRequest::set_end(int64_t value) {
  _internal_set_end(value);
  // @@protoc_insertion_point(field_set:task.TaskRequest.end)
}

// int64 step = 4;
inline void TaskRequest::clear_step() {
  _impl_.step_ = int64_t{0};
}
inline int64_t TaskRequest::_internal_step() const {
  return _impl_.step_;
}
inline int64_t TaskRequest::step() const {
  // @@protoc_insertion_point(field_get:task.TaskRequest.step)
  return _internal_step();
}
inline void TaskRequest::_internal_set_step(int64_t value) {
  
  _impl_.step_ = value;
}
inline void TaskRequest::set_step(int64_t value) {
  _internal_set_step(value);
  // @@protoc_insertion_point(field_set:task.TaskRequest.step)
}

// bytes environment_data = 5;
inline void TaskRequest::clear_environment_data() {
  _impl_.environment_data_.ClearToEmpty();
}
inline const std::string& TaskRequest::environment_data() const {
  // @@protoc_insertion_point(field_get:task.TaskRequest.environment_data)
  return _internal_environment_data();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void TaskRequest::set_environment_data(ArgT0&& arg0, ArgT... args) {
 
 _impl_.environment_data_.SetBytes(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:task.TaskRequest.environment_data)
}
inline std::string* TaskRequest::mutable_environment_data() {
  std::string* _s = _internal_mutable_environment_data();
  // @@protoc_insertion_point(field_mutable:task.TaskRequest.environment_data)
  return _s;
}
inline const std::string& TaskRequest::_internal_environment_data() const {
  return _impl_.environment_data_.Get();
}
inline void TaskRequest::_internal_set_environment_data(const std::string& value) {
  
  _impl_.environment_data_.Set(value, GetArenaForAllocation());
}
inline std::string* TaskRequest::_internal_mutable_environment_data() {
  
  return _impl_.environment_data_.Mutable(GetArenaForAllocation());
}
inline std::string* TaskRequest::release_environment_data() {
  // @@protoc_insertion_point(field_release:task.TaskRequest.environment_data)
  return _impl_.environment_data_.Release();
}
inline void TaskRequest::set_allocated_environment_data(std::string* environment_data) {
  if (environment_data != nullptr) {
    
  } else {
    
  }
  _impl_.environment_data_.SetAllocated(environment_data, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.environment_data_.IsDefault()) {
    _impl_.environment_data_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:task.TaskRequest.environment_data)
}

// uint64 environment_size = 6;
inline void TaskRequest::clear_environment_size() {
  _impl_.environment_size_ = uint64_t{0u};
}
inline uint64_t TaskRequest::_internal_environment_size() const {
  return _impl_.environment_size_;
}
inline uint64_t TaskRequest::environment_size() const {
  // @@protoc_insertion_point(field_get:task.TaskRequest.environment_size)
  return _internal_environment_size();
}
inline void TaskRequest::_internal_set_environment_size(uint64_t value) {
  
  _impl_.environment_size_ = value;
}
inline void TaskRequest::set_environment_size(uint64_t value) {
  _internal_set_environment_size(value);
  // @@protoc_insertion_point(field_set:task.TaskRequest.environment_size)
}

// string function_name = 7;
inline void TaskRequest::clear_function_name() {
  _impl_.function_name_.ClearToEmpty();
}
inline const std::string& TaskRequest::function_name() const {
  // @@protoc_insertion_point(field_get:task.TaskRequest.function_name)
  return _internal_function_name();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void TaskRequest::set_function_name(ArgT0&& arg0, ArgT... args) {
 
 _impl_.function_name_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:task.TaskRequest.function_name)
}
inline std::string* TaskRequest::mutable_function_name() {
  std::string* _s = _internal_mutable_function_name();
  // @@protoc_insertion_point(field_mutable:task.TaskRequest.function_name)
  return _s;
}
inline const std::string& TaskRequest::_internal_function_name() const {
  return _impl_.function_name_.Get();
}
inline void TaskRequest::_internal_set_function_name(const std::string& value) {
  
  _impl_.function_name_.Set(value, GetArenaForAllocation());
}
inline std::string* TaskRequest::_internal_mutable_function_name() {
  
  return _impl_.function_name_.Mutable(GetArenaForAllocation());
}
inline std::string* TaskRequest::release_function_name() {
  // @@protoc_insertion_point(field_release:task.TaskRequest.function_name)
  return _impl_.function_name_.Release();
}
inline void TaskRequest::set_allocated_function_name(std::string* function_name) {
  if (function_name != nullptr) {
    
  } else {
    
  }
  _impl_.function_name_.SetAllocated(function_name, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.function_name_.IsDefault()) {
    _impl_.function_name_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:task.TaskRequest.function_name)
}

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// TaskResponse

// int64 task_id = 1;
inline void TaskResponse::clear_task_id() {
  _impl_.task_id_ = int64_t{0};
}
inline int64_t TaskResponse::_internal_task_id() const {
  return _impl_.task_id_;
}
inline int64_t TaskResponse::task_id() const {
  // @@protoc_insertion_point(field_get:task.TaskResponse.task_id)
  return _internal_task_id();
}
inline void TaskResponse::_internal_set_task_id(int64_t value) {
  
  _impl_.task_id_ = value;
}
inline void TaskResponse::set_task_id(int64_t value) {
  _internal_set_task_id(value);
  // @@protoc_insertion_point(field_set:task.TaskResponse.task_id)
}

// bool success = 2;
inline void TaskResponse::clear_success() {
  _impl_.success_ = false;
}
inline bool TaskResponse::_internal_success() const {
  return _impl_.success_;
}
inline bool TaskResponse::success() const {
  // @@protoc_insertion_point(field_get:task.TaskResponse.success)
  return _internal_success();
}
inline void TaskResponse::_internal_set_success(bool value) {
  
  _impl_.success_ = value;
}
inline void TaskResponse::set_success(bool value) {
  _internal_set_success(value);
  // @@protoc_insertion_point(field_set:task.TaskResponse.success)
}

// bytes result_data = 3;
inline void TaskResponse::clear_result_data() {
  _impl_.result_data_.ClearToEmpty();
}
inline const std::string& TaskResponse::result_data() const {
  // @@protoc_insertion_point(field_get:task.TaskResponse.result_data)
  return _internal_result_data();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void TaskResponse::set_result_data(ArgT0&& arg0, ArgT... args) {
 
 _impl_.result_data_.SetBytes(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:task.TaskResponse.result_data)
}
inline std::string* TaskResponse::mutable_result_data() {
  std::string* _s = _internal_mutable_result_data();
  // @@protoc_insertion_point(field_mutable:task.TaskResponse.result_data)
  return _s;
}
inline const std::string& TaskResponse::_internal_result_data() const {
  return _impl_.result_data_.Get();
}
inline void TaskResponse::_internal_set_result_data(const std::string& value) {
  
  _impl_.result_data_.Set(value, GetArenaForAllocation());
}
inline std::string* TaskResponse::_internal_mutable_result_data() {
  
  return _impl_.result_data_.Mutable(GetArenaForAllocation());
}
inline std::string* TaskResponse::release_result_data() {
  // @@protoc_insertion_point(field_release:task.TaskResponse.result_data)
  return _impl_.result_data_.Release();
}
inline void TaskResponse::set_allocated_result_data(std::string* result_data) {
  if (result_data != nullptr) {
    
  } else {
    
  }
  _impl_.result_data_.SetAllocated(result_data, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.result_data_.IsDefault()) {
    _impl_.result_data_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:task.TaskResponse.result_data)
}

// uint64 result_size = 4;
inline void TaskResponse::clear_result_size() {
  _impl_.result_size_ = uint64_t{0u};
}
inline uint64_t TaskResponse::_internal_result_size() const {
  return _impl_.result_size_;
}
inline uint64_t TaskResponse::result_size() const {
  // @@protoc_insertion_point(field_get:task.TaskResponse.result_size)
  return _internal_result_size();
}
inline void TaskResponse::_internal_set_result_size(uint64_t value) {
  
  _impl_.result_size_ = value;
}
inline void TaskResponse::set_result_size(uint64_t value) {
  _internal_set_result_size(value);
  // @@protoc_insertion_point(field_set:task.TaskResponse.result_size)
}

// string error_message = 5;
inline void TaskResponse::clear_error_message() {
  _impl_.error_message_.ClearToEmpty();
}
inline const std::string& TaskResponse::error_message() const {
  // @@protoc_insertion_point(field_get:task.TaskResponse.error_message)
  return _internal_error_message();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void TaskResponse::set_error_message(ArgT0&& arg0, ArgT... args) {
 
 _impl_.error_message_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:task.TaskResponse.error_message)
}
inline std::string* TaskResponse::mutable_error_message() {
  std::string* _s = _internal_mutable_error_message();
  // @@protoc_insertion_point(field_mutable:task.TaskResponse.error_message)
  return _s;
}
inline const std::string& TaskResponse::_internal_error_message() const {
  return _impl_.error_message_.Get();
}
inline void TaskResponse::_internal_set_error_message(const std::string& value) {
  
  _impl_.error_message_.Set(value, GetArenaForAllocation());
}
inline std::string* TaskResponse::_internal_mutable_error_message() {
  
  return _impl_.error_message_.Mutable(GetArenaForAllocation());
}
inline std::string* TaskResponse::release_error_message() {
  // @@protoc_insertion_point(field_release:task.TaskResponse.error_message)
  return _impl_.error_message_.Release();
}
inline void TaskResponse::set_allocated_error_message(std::string* error_message) {
  if (error_message != nullptr) {
    
  } else {
    
  }
  _impl_.error_message_.SetAllocated(error_message, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.error_message_.IsDefault()) {
    _impl_.error_message_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:task.TaskResponse.error_message)
}

// map<int64, bytes> iteration_outputs = 6;
inline int TaskResponse::_internal_iteration_outputs_size() const {
  return _impl_.iteration_outputs_.size();
}
inline int TaskResponse::iteration_outputs_size() const {
  return _internal_iteration_outputs_size();
}
inline void TaskResponse::clear_iteration_outputs() {
  _impl_.iteration_outputs_.Clear();
}
inline const ::PROTOBUF_NAMESPACE_ID::Map< int64_t, std::string >&
TaskResponse::_internal_iteration_outputs() const {
  return _impl_.iteration_outputs_.GetMap();
}
inline const ::PROTOBUF_NAMESPACE_ID::Map< int64_t, std::string >&
TaskResponse::iteration_outputs() const {
  // @@protoc_insertion_point(field_map:task.TaskResponse.iteration_outputs)
  return _internal_iteration_outputs();
}
inline ::PROTOBUF_NAMESPACE_ID::Map< int64_t, std::string >*
TaskResponse::_internal_mutable_iteration_outputs() {
  return _impl_.iteration_outputs_.MutableMap();
}
inline ::PROTOBUF_NAMESPACE_ID::Map< int64_t, std::string >*
TaskResponse::mutable_iteration_outputs() {
  // @@protoc_insertion_point(field_mutable_map:task.TaskResponse.iteration_outputs)
  return _internal_mutable_iteration_outputs();
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__
// -------------------------------------------------------------------

// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)

}  // namespace task

// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // GOOGLE_PROTOBUF_INCLUDED_GOOGLE_PROTOBUF_INCLUDED_task_5fservice_2eproto
