// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: task_service.proto

#include "task_service.pb.h"
#include "task_service.grpc.pb.h"

#include <functional>
#include <grpcpp/support/async_stream.h>
#include <grpcpp/support/async_unary_call.h>
#include <grpcpp/impl/channel_interface.h>
#include <grpcpp/impl/client_unary_call.h>
#include <grpcpp/support/client_callback.h>
#include <grpcpp/support/message_allocator.h>
#include <grpcpp/support/method_handler.h>
#include <grpcpp/impl/rpc_service_method.h>
#include <grpcpp/support/server_callback.h>
#include <grpcpp/impl/server_callback_handlers.h>
#include <grpcpp/server_context.h>
#include <grpcpp/impl/service_type.h>
#include <grpcpp/support/sync_stream.h>
namespace task {

static const char* TaskService_method_names[] = {
  "/task.TaskService/ExecuteTask",
};

std::unique_ptr< TaskService::Stub> TaskService::NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options) {
  (void)options;
  std::unique_ptr< TaskService::Stub> stub(new TaskService::Stub(channel, options));
  return stub;
}

TaskService::Stub::Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options)
  : channel_(channel), rpcmethod_ExecuteTask_(TaskService_method_names[0], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  {}

::grpc::Status TaskService::Stub::ExecuteTask(::grpc::ClientContext* context, const ::task::TaskRequest& request, ::task::TaskResponse* response) {
  return ::grpc::internal::BlockingUnaryCall< ::task::TaskRequest, ::task::TaskResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_ExecuteTask_, context, request, response);
}

void TaskService::Stub::async::ExecuteTask(::grpc::ClientContext* context, const ::task::TaskRequest* request, ::task::TaskResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::task::TaskRequest, ::task::TaskResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_ExecuteTask_, context, request, response, std::move(f));
}

void TaskService::Stub::async::ExecuteTask(::grpc::ClientContext* context, const ::task::TaskRequest* request, ::task::TaskResponse* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_ExecuteTask_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::task::TaskResponse>* TaskService::Stub::PrepareAsyncExecuteTaskRaw(::grpc::ClientContext* context, const ::task::TaskRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::task::TaskResponse, ::task::TaskRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_ExecuteTask_, context, request);
}

::grpc::ClientAsyncResponseReader< ::task::TaskResponse>* TaskService::Stub::AsyncExecuteTaskRaw(::grpc::ClientContext* context, const ::task::TaskRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncExecuteTaskRaw(context, request, cq);
  result->StartCall();
  return result;
}

TaskService::Service::Service() {
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      TaskService_method_names[0],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< TaskService::Service, ::task::TaskRequest, ::task::TaskResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](TaskService::Service* service,
             ::grpc::ServerContext* ctx,
             const ::task::TaskRequest* req,
             ::task::TaskResponse* resp) {
               return service->ExecuteTask(ctx, req, resp);
             }, this)));
}

TaskService::Service::~Service() {
}

::grpc::Status TaskService::Service::ExecuteTask(::grpc::ServerContext* context, const ::task::TaskRequest* request, ::task::TaskResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}


}  // namespace task

