// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: task_service.proto
// Protobuf C++ Version: 5.29.5

#ifndef task_5fservice_2eproto_2epb_2eh
#define task_5fservice_2eproto_2epb_2eh

#include <limits>
#include <string>
#include <type_traits>
#include <utility>

#include "google/protobuf/runtime_version.h"
#if PROTOBUF_VERSION != 5029005
#error "Protobuf C++ gencode is built with an incompatible version of"
#error "Protobuf C++ headers/runtime. See"
#error "https://protobuf.dev/support/cross-version-runtime-guarantee/#cpp"
#endif
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/arena.h"
#include "google/protobuf/arenastring.h"
#include "google/protobuf/generated_message_tctable_decl.h"
#include "google/protobuf/generated_message_util.h"
#include "google/protobuf/metadata_lite.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/message.h"
#include "google/protobuf/message_lite.h"
#include "google/protobuf/repeated_field.h"  // IWYU pragma: export
#include "google/protobuf/extension_set.h"  // IWYU pragma: export
#include "google/protobuf/map.h"  // IWYU pragma: export
#include "google/protobuf/map_entry.h"
#include "google/protobuf/map_field_inl.h"
#include "google/protobuf/unknown_field_set.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"

#define PROTOBUF_INTERNAL_EXPORT_task_5fservice_2eproto

namespace google {
namespace protobuf {
namespace internal {
template <typename T>
::absl::string_view GetAnyMessageName();
}  // namespace internal
}  // namespace protobuf
}  // namespace google

// Internal implementation detail -- do not use these members.
struct TableStruct_task_5fservice_2eproto {
  static const ::uint32_t offsets[];
};
extern const ::google::protobuf::internal::DescriptorTable
    descriptor_table_task_5fservice_2eproto;
namespace task {
class EnvArrayField;
struct EnvArrayFieldDefaultTypeInternal;
extern EnvArrayFieldDefaultTypeInternal _EnvArrayField_default_instance_;
class TaskRequest;
struct TaskRequestDefaultTypeInternal;
extern TaskRequestDefaultTypeInternal _TaskRequest_default_instance_;
class TaskResponse;
struct TaskResponseDefaultTypeInternal;
extern TaskResponseDefaultTypeInternal _TaskResponse_default_instance_;
class TaskResponse_IterationOutputsEntry_DoNotUse;
struct TaskResponse_IterationOutputsEntry_DoNotUseDefaultTypeInternal;
extern TaskResponse_IterationOutputsEntry_DoNotUseDefaultTypeInternal _TaskResponse_IterationOutputsEntry_DoNotUse_default_instance_;
}  // namespace task
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google

namespace task {

// ===================================================================


// -------------------------------------------------------------------

class TaskResponse_IterationOutputsEntry_DoNotUse final
    : public ::google::protobuf::internal::MapEntry<
          ::int64_t, std::string,
          ::google::protobuf::internal::WireFormatLite::TYPE_INT64,
          ::google::protobuf::internal::WireFormatLite::TYPE_BYTES> {
 public:
  using SuperType = ::google::protobuf::internal::MapEntry<
      ::int64_t, std::string,
      ::google::protobuf::internal::WireFormatLite::TYPE_INT64,
      ::google::protobuf::internal::WireFormatLite::TYPE_BYTES>;
  TaskResponse_IterationOutputsEntry_DoNotUse();
  template <typename = void>
  explicit PROTOBUF_CONSTEXPR TaskResponse_IterationOutputsEntry_DoNotUse(
      ::google::protobuf::internal::ConstantInitialized);
  explicit TaskResponse_IterationOutputsEntry_DoNotUse(::google::protobuf::Arena* arena);
  static const TaskResponse_IterationOutputsEntry_DoNotUse* internal_default_instance() {
    return reinterpret_cast<const TaskResponse_IterationOutputsEntry_DoNotUse*>(
        &_TaskResponse_IterationOutputsEntry_DoNotUse_default_instance_);
  }


 private:
  friend class ::google::protobuf::MessageLite;
  friend struct ::TableStruct_task_5fservice_2eproto;

  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<
      1, 2, 0,
      0, 2>
      _table_;

  const ::google::protobuf::internal::ClassData* GetClassData() const PROTOBUF_FINAL;
  static void* PlacementNew_(const void*, void* mem,
                             ::google::protobuf::Arena* arena);
  static constexpr auto InternalNewImpl_();
  static const ::google::protobuf::internal::ClassDataFull _class_data_;
};
// -------------------------------------------------------------------

class EnvArrayField final : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:task.EnvArrayField) */ {
 public:
  inline EnvArrayField() : EnvArrayField(nullptr) {}
  ~EnvArrayField() PROTOBUF_FINAL;

#if defined(PROTOBUF_CUSTOM_VTABLE)
  void operator delete(EnvArrayField* msg, std::destroying_delete_t) {
    SharedDtor(*msg);
    ::google::protobuf::internal::SizedDelete(msg, sizeof(EnvArrayField));
  }
#endif

  template <typename = void>
  explicit PROTOBUF_CONSTEXPR EnvArrayField(
      ::google::protobuf::internal::ConstantInitialized);

  inline EnvArrayField(const EnvArrayField& from) : EnvArrayField(nullptr, from) {}
  inline EnvArrayField(EnvArrayField&& from) noexcept
      : EnvArrayField(nullptr, std::move(from)) {}
  inline EnvArrayField& operator=(const EnvArrayField& from) {
    CopyFrom(from);
    return *this;
  }
  inline EnvArrayField& operator=(EnvArrayField&& from) noexcept {
    if (this == &from) return *this;
    if (::google::protobuf::internal::CanMoveWithInternalSwap(GetArena(), from.GetArena())) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const EnvArrayField& default_instance() {
    return *internal_default_instance();
  }
  static inline const EnvArrayField* internal_default_instance() {
    return reinterpret_cast<const EnvArrayField*>(
        &_EnvArrayField_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 3;
  friend void swap(EnvArrayField& a, EnvArrayField& b) { a.Swap(&b); }
  inline void Swap(EnvArrayField* other) {
    if (other == this) return;
    if (::google::protobuf::internal::CanUseInternalSwap(GetArena(), other->GetArena())) {
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(EnvArrayField* other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  EnvArrayField* New(::google::protobuf::Arena* arena = nullptr) const {
    return ::google::protobuf::Message::DefaultConstruct<EnvArrayField>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const EnvArrayField& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const EnvArrayField& from) { EnvArrayField::MergeImpl(*this, from); }

  private:
  static void MergeImpl(
      ::google::protobuf::MessageLite& to_msg,
      const ::google::protobuf::MessageLite& from_msg);

  public:
  bool IsInitialized() const {
    return true;
  }
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() PROTOBUF_FINAL;
  #if defined(PROTOBUF_CUSTOM_VTABLE)
  private:
  static ::size_t ByteSizeLong(const ::google::protobuf::MessageLite& msg);
  static ::uint8_t* _InternalSerialize(
      const MessageLite& msg, ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream);

  public:
  ::size_t ByteSizeLong() const { return ByteSizeLong(*this); }
  ::uint8_t* _InternalSerialize(
      ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream) const {
    return _InternalSerialize(*this, target, stream);
  }
  #else   // PROTOBUF_CUSTOM_VTABLE
  ::size_t ByteSizeLong() const final;
  ::uint8_t* _InternalSerialize(
      ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream) const final;
  #endif  // PROTOBUF_CUSTOM_VTABLE
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* arena);
  static void SharedDtor(MessageLite& self);
  void InternalSwap(EnvArrayField* other);
 private:
  template <typename T>
  friend ::absl::string_view(
      ::google::protobuf::internal::GetAnyMessageName)();
  static ::absl::string_view FullMessageName() { return "task.EnvArrayField"; }

 protected:
  explicit EnvArrayField(::google::protobuf::Arena* arena);
  EnvArrayField(::google::protobuf::Arena* arena, const EnvArrayField& from);
  EnvArrayField(::google::protobuf::Arena* arena, EnvArrayField&& from) noexcept
      : EnvArrayField(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::internal::ClassData* GetClassData() const PROTOBUF_FINAL;
  static void* PlacementNew_(const void*, void* mem,
                             ::google::protobuf::Arena* arena);
  static constexpr auto InternalNewImpl_();
  static const ::google::protobuf::internal::ClassDataFull _class_data_;

 public:
  ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kDataFieldNumber = 3,
    kLengthFieldNumber = 2,
    kFieldIndexFieldNumber = 1,
  };
  // bytes data = 3;
  void clear_data() ;
  const std::string& data() const;
  template <typename Arg_ = const std::string&, typename... Args_>
  void set_data(Arg_&& arg, Args_... args);
  std::string* mutable_data();
  PROTOBUF_NODISCARD std::string* release_data();
  void set_allocated_data(std::string* value);

  private:
  const std::string& _internal_data() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_data(
      const std::string& value);
  std::string* _internal_mutable_data();

  public:
  // uint64 length = 2;
  void clear_length() ;
  ::uint64_t length() const;
  void set_length(::uint64_t value);

  private:
  ::uint64_t _internal_length() const;
  void _internal_set_length(::uint64_t value);

  public:
  // uint32 field_index = 1;
  void clear_field_index() ;
  ::uint32_t field_index() const;
  void set_field_index(::uint32_t value);

  private:
  ::uint32_t _internal_field_index() const;
  void _internal_set_field_index(::uint32_t value);

  public:
  // @@protoc_insertion_point(class_scope:task.EnvArrayField)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<
      2, 3, 0,
      0, 2>
      _table_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(
        ::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                          ::google::protobuf::Arena* arena);
    inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                          ::google::protobuf::Arena* arena, const Impl_& from,
                          const EnvArrayField& from_msg);
    ::google::protobuf::internal::ArenaStringPtr data_;
    ::uint64_t length_;
    ::uint32_t field_index_;
    ::google::protobuf::internal::CachedSize _cached_size_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_task_5fservice_2eproto;
};
// -------------------------------------------------------------------

class TaskResponse final : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:task.TaskResponse) */ {
 public:
  inline TaskResponse() : TaskResponse(nullptr) {}
  ~TaskResponse() PROTOBUF_FINAL;

#if defined(PROTOBUF_CUSTOM_VTABLE)
  void operator delete(TaskResponse* msg, std::destroying_delete_t) {
    SharedDtor(*msg);
    ::google::protobuf::internal::SizedDelete(msg, sizeof(TaskResponse));
  }
#endif

  template <typename = void>
  explicit PROTOBUF_CONSTEXPR TaskResponse(
      ::google::protobuf::internal::ConstantInitialized);

  inline TaskResponse(const TaskResponse& from) : TaskResponse(nullptr, from) {}
  inline TaskResponse(TaskResponse&& from) noexcept
      : TaskResponse(nullptr, std::move(from)) {}
  inline TaskResponse& operator=(const TaskResponse& from) {
    CopyFrom(from);
    return *this;
  }
  inline TaskResponse& operator=(TaskResponse&& from) noexcept {
    if (this == &from) return *this;
    if (::google::protobuf::internal::CanMoveWithInternalSwap(GetArena(), from.GetArena())) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const TaskResponse& default_instance() {
    return *internal_default_instance();
  }
  static inline const TaskResponse* internal_default_instance() {
    return reinterpret_cast<const TaskResponse*>(
        &_TaskResponse_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 2;
  friend void swap(TaskResponse& a, TaskResponse& b) { a.Swap(&b); }
  inline void Swap(TaskResponse* other) {
    if (other == this) return;
    if (::google::protobuf::internal::CanUseInternalSwap(GetArena(), other->GetArena())) {
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(TaskResponse* other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  TaskResponse* New(::google::protobuf::Arena* arena = nullptr) const {
    return ::google::protobuf::Message::DefaultConstruct<TaskResponse>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const TaskResponse& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const TaskResponse& from) { TaskResponse::MergeImpl(*this, from); }

  private:
  static void MergeImpl(
      ::google::protobuf::MessageLite& to_msg,
      const ::google::protobuf::MessageLite& from_msg);

  public:
  bool IsInitialized() const {
    return true;
  }
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() PROTOBUF_FINAL;
  #if defined(PROTOBUF_CUSTOM_VTABLE)
  private:
  static ::size_t ByteSizeLong(const ::google::protobuf::MessageLite& msg);
  static ::uint8_t* _InternalSerialize(
      const MessageLite& msg, ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream);

  public:
  ::size_t ByteSizeLong() const { return ByteSizeLong(*this); }
  ::uint8_t* _InternalSerialize(
      ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream) const {
    return _InternalSerialize(*this, target, stream);
  }
  #else   // PROTOBUF_CUSTOM_VTABLE
  ::size_t ByteSizeLong() const final;
  ::uint8_t* _InternalSerialize(
      ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream) const final;
  #endif  // PROTOBUF_CUSTOM_VTABLE
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* arena);
  static void SharedDtor(MessageLite& self);
  void InternalSwap(TaskResponse* other);
 private:
  template <typename T>
  friend ::absl::string_view(
      ::google::protobuf::internal::GetAnyMessageName)();
  static ::absl::string_view FullMessageName() { return "task.TaskResponse"; }

 protected:
  explicit TaskResponse(::google::protobuf::Arena* arena);
  TaskResponse(::google::protobuf::Arena* arena, const TaskResponse& from);
  TaskResponse(::google::protobuf::Arena* arena, TaskResponse&& from) noexcept
      : TaskResponse(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::internal::ClassData* GetClassData() const PROTOBUF_FINAL;
  static void* PlacementNew_(const void*, void* mem,
                             ::google::protobuf::Arena* arena);
  static constexpr auto InternalNewImpl_();
  static const ::google::protobuf::internal::ClassDataFull _class_data_;

 public:
  ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kIterationOutputsFieldNumber = 6,
    kArraysFieldNumber = 7,
    kResultDataFieldNumber = 3,
    kErrorMessageFieldNumber = 5,
    kTaskIdFieldNumber = 1,
    kResultSizeFieldNumber = 4,
    kSuccessFieldNumber = 2,
  };
  // map<int64, bytes> iteration_outputs = 6;
  int iteration_outputs_size() const;
  private:
  int _internal_iteration_outputs_size() const;

  public:
  void clear_iteration_outputs() ;
  const ::google::protobuf::Map<::int64_t, std::string>& iteration_outputs() const;
  ::google::protobuf::Map<::int64_t, std::string>* mutable_iteration_outputs();

  private:
  const ::google::protobuf::Map<::int64_t, std::string>& _internal_iteration_outputs() const;
  ::google::protobuf::Map<::int64_t, std::string>* _internal_mutable_iteration_outputs();

  public:
  // repeated .task.EnvArrayField arrays = 7;
  int arrays_size() const;
  private:
  int _internal_arrays_size() const;

  public:
  void clear_arrays() ;
  ::task::EnvArrayField* mutable_arrays(int index);
  ::google::protobuf::RepeatedPtrField<::task::EnvArrayField>* mutable_arrays();

  private:
  const ::google::protobuf::RepeatedPtrField<::task::EnvArrayField>& _internal_arrays() const;
  ::google::protobuf::RepeatedPtrField<::task::EnvArrayField>* _internal_mutable_arrays();
  public:
  const ::task::EnvArrayField& arrays(int index) const;
  ::task::EnvArrayField* add_arrays();
  const ::google::protobuf::RepeatedPtrField<::task::EnvArrayField>& arrays() const;
  // bytes result_data = 3;
  void clear_result_data() ;
  const std::string& result_data() const;
  template <typename Arg_ = const std::string&, typename... Args_>
  void set_result_data(Arg_&& arg, Args_... args);
  std::string* mutable_result_data();
  PROTOBUF_NODISCARD std::string* release_result_data();
  void set_allocated_result_data(std::string* value);

  private:
  const std::string& _internal_result_data() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_result_data(
      const std::string& value);
  std::string* _internal_mutable_result_data();

  public:
  // string error_message = 5;
  void clear_error_message() ;
  const std::string& error_message() const;
  template <typename Arg_ = const std::string&, typename... Args_>
  void set_error_message(Arg_&& arg, Args_... args);
  std::string* mutable_error_message();
  PROTOBUF_NODISCARD std::string* release_error_message();
  void set_allocated_error_message(std::string* value);

  private:
  const std::string& _internal_error_message() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_error_message(
      const std::string& value);
  std::string* _internal_mutable_error_message();

  public:
  // int64 task_id = 1;
  void clear_task_id() ;
  ::int64_t task_id() const;
  void set_task_id(::int64_t value);

  private:
  ::int64_t _internal_task_id() const;
  void _internal_set_task_id(::int64_t value);

  public:
  // uint64 result_size = 4;
  void clear_result_size() ;
  ::uint64_t result_size() const;
  void set_result_size(::uint64_t value);

  private:
  ::uint64_t _internal_result_size() const;
  void _internal_set_result_size(::uint64_t value);

  public:
  // bool success = 2;
  void clear_success() ;
  bool success() const;
  void set_success(bool value);

  private:
  bool _internal_success() const;
  void _internal_set_success(bool value);

  public:
  // @@protoc_insertion_point(class_scope:task.TaskResponse)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<
      3, 7, 2,
      39, 2>
      _table_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(
        ::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                          ::google::protobuf::Arena* arena);
    inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                          ::google::protobuf::Arena* arena, const Impl_& from,
                          const TaskResponse& from_msg);
    ::google::protobuf::internal::MapField<TaskResponse_IterationOutputsEntry_DoNotUse, ::int64_t, std::string,
                      ::google::protobuf::internal::WireFormatLite::TYPE_INT64,
                      ::google::protobuf::internal::WireFormatLite::TYPE_BYTES>
        iteration_outputs_;
    ::google::protobuf::RepeatedPtrField< ::task::EnvArrayField > arrays_;
    ::google::protobuf::internal::ArenaStringPtr result_data_;
    ::google::protobuf::internal::ArenaStringPtr error_message_;
    ::int64_t task_id_;
    ::uint64_t result_size_;
    bool success_;
    ::google::protobuf::internal::CachedSize _cached_size_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_task_5fservice_2eproto;
};
// -------------------------------------------------------------------

class TaskRequest final : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:task.TaskRequest) */ {
 public:
  inline TaskRequest() : TaskRequest(nullptr) {}
  ~TaskRequest() PROTOBUF_FINAL;

#if defined(PROTOBUF_CUSTOM_VTABLE)
  void operator delete(TaskRequest* msg, std::destroying_delete_t) {
    SharedDtor(*msg);
    ::google::protobuf::internal::SizedDelete(msg, sizeof(TaskRequest));
  }
#endif

  template <typename = void>
  explicit PROTOBUF_CONSTEXPR TaskRequest(
      ::google::protobuf::internal::ConstantInitialized);

  inline TaskRequest(const TaskRequest& from) : TaskRequest(nullptr, from) {}
  inline TaskRequest(TaskRequest&& from) noexcept
      : TaskRequest(nullptr, std::move(from)) {}
  inline TaskRequest& operator=(const TaskRequest& from) {
    CopyFrom(from);
    return *this;
  }
  inline TaskRequest& operator=(TaskRequest&& from) noexcept {
    if (this == &from) return *this;
    if (::google::protobuf::internal::CanMoveWithInternalSwap(GetArena(), from.GetArena())) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const TaskRequest& default_instance() {
    return *internal_default_instance();
  }
  static inline const TaskRequest* internal_default_instance() {
    return reinterpret_cast<const TaskRequest*>(
        &_TaskRequest_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 0;
  friend void swap(TaskRequest& a, TaskRequest& b) { a.Swap(&b); }
  inline void Swap(TaskRequest* other) {
    if (other == this) return;
    if (::google::protobuf::internal::CanUseInternalSwap(GetArena(), other->GetArena())) {
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(TaskRequest* other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  TaskRequest* New(::google::protobuf::Arena* arena = nullptr) const {
    return ::google::protobuf::Message::DefaultConstruct<TaskRequest>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const TaskRequest& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const TaskRequest& from) { TaskRequest::MergeImpl(*this, from); }

  private:
  static void MergeImpl(
      ::google::protobuf::MessageLite& to_msg,
      const ::google::protobuf::MessageLite& from_msg);

  public:
  bool IsInitialized() const {
    return true;
  }
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() PROTOBUF_FINAL;
  #if defined(PROTOBUF_CUSTOM_VTABLE)
  private:
  static ::size_t ByteSizeLong(const ::google::protobuf::MessageLite& msg);
  static ::uint8_t* _InternalSerialize(
      const MessageLite& msg, ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream);

  public:
  ::size_t ByteSizeLong() const { return ByteSizeLong(*this); }
  ::uint8_t* _InternalSerialize(
      ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream) const {
    return _InternalSerialize(*this, target, stream);
  }
  #else   // PROTOBUF_CUSTOM_VTABLE
  ::size_t ByteSizeLong() const final;
  ::uint8_t* _InternalSerialize(
      ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream) const final;
  #endif  // PROTOBUF_CUSTOM_VTABLE
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* arena);
  static void SharedDtor(MessageLite& self);
  void InternalSwap(TaskRequest* other);
 private:
  template <typename T>
  friend ::absl::string_view(
      ::google::protobuf::internal::GetAnyMessageName)();
  static ::absl::string_view FullMessageName() { return "task.TaskRequest"; }

 protected:
  explicit TaskRequest(::google::protobuf::Arena* arena);
  TaskRequest(::google::protobuf::Arena* arena, const TaskRequest& from);
  TaskRequest(::google::protobuf::Arena* arena, TaskRequest&& from) noexcept
      : TaskRequest(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::internal::ClassData* GetClassData() const PROTOBUF_FINAL;
  static void* PlacementNew_(const void*, void* mem,
                             ::google::protobuf::Arena* arena);
  static constexpr auto InternalNewImpl_();
  static const ::google::protobuf::internal::ClassDataFull _class_data_;

 public:
  ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kArraysFieldNumber = 10,
    kEnvironmentDataFieldNumber = 5,
    kFunctionNameFieldNumber = 7,
    kIrDataFieldNumber = 8,
    kIrFormatFieldNumber = 9,
    kTaskIdFieldNumber = 1,
    kStartFieldNumber = 2,
    kEndFieldNumber = 3,
    kStepFieldNumber = 4,
    kEnvironmentSizeFieldNumber = 6,
  };
  // repeated .task.EnvArrayField arrays = 10;
  int arrays_size() const;
  private:
  int _internal_arrays_size() const;

  public:
  void clear_arrays() ;
  ::task::EnvArrayField* mutable_arrays(int index);
  ::google::protobuf::RepeatedPtrField<::task::EnvArrayField>* mutable_arrays();

  private:
  const ::google::protobuf::RepeatedPtrField<::task::EnvArrayField>& _internal_arrays() const;
  ::google::protobuf::RepeatedPtrField<::task::EnvArrayField>* _internal_mutable_arrays();
  public:
  const ::task::EnvArrayField& arrays(int index) const;
  ::task::EnvArrayField* add_arrays();
  const ::google::protobuf::RepeatedPtrField<::task::EnvArrayField>& arrays() const;
  // bytes environment_data = 5;
  void clear_environment_data() ;
  const std::string& environment_data() const;
  template <typename Arg_ = const std::string&, typename... Args_>
  void set_environment_data(Arg_&& arg, Args_... args);
  std::string* mutable_environment_data();
  PROTOBUF_NODISCARD std::string* release_environment_data();
  void set_allocated_environment_data(std::string* value);

  private:
  const std::string& _internal_environment_data() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_environment_data(
      const std::string& value);
  std::string* _internal_mutable_environment_data();

  public:
  // string function_name = 7;
  void clear_function_name() ;
  const std::string& function_name() const;
  template <typename Arg_ = const std::string&, typename... Args_>
  void set_function_name(Arg_&& arg, Args_... args);
  std::string* mutable_function_name();
  PROTOBUF_NODISCARD std::string* release_function_name();
  void set_allocated_function_name(std::string* value);

  private:
  const std::string& _internal_function_name() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_function_name(
      const std::string& value);
  std::string* _internal_mutable_function_name();

  public:
  // bytes ir_data = 8;
  void clear_ir_data() ;
  const std::string& ir_data() const;
  template <typename Arg_ = const std::string&, typename... Args_>
  void set_ir_data(Arg_&& arg, Args_... args);
  std::string* mutable_ir_data();
  PROTOBUF_NODISCARD std::string* release_ir_data();
  void set_allocated_ir_data(std::string* value);

  private:
  const std::string& _internal_ir_data() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_ir_data(
      const std::string& value);
  std::string* _internal_mutable_ir_data();

  public:
  // string ir_format = 9;
  void clear_ir_format() ;
  const std::string& ir_format() const;
  template <typename Arg_ = const std::string&, typename... Args_>
  void set_ir_format(Arg_&& arg, Args_... args);
  std::string* mutable_ir_format();
  PROTOBUF_NODISCARD std::string* release_ir_format();
  void set_allocated_ir_format(std::string* value);

  private:
  const std::string& _internal_ir_format() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_ir_format(
      const std::string& value);
  std::string* _internal_mutable_ir_format();

  public:
  // int64 task_id = 1;
  void clear_task_id() ;
  ::int64_t task_id() const;
  void set_task_id(::int64_t value);

  private:
  ::int64_t _internal_task_id() const;
  void _internal_set_task_id(::int64_t value);

  public:
  // int64 start = 2;
  void clear_start() ;
  ::int64_t start() const;
  void set_start(::int64_t value);

  private:
  ::int64_t _internal_start() const;
  void _internal_set_start(::int64_t value);

  public:
  // int64 end = 3;
  void clear_end() ;
  ::int64_t end() const;
  void set_end(::int64_t value);

  private:
  ::int64_t _internal_end() const;
  void _internal_set_end(::int64_t value);

  public:
  // int64 step = 4;
  void clear_step() ;
  ::int64_t step() const;
  void set_step(::int64_t value);

  private:
  ::int64_t _internal_step() const;
  void _internal_set_step(::int64_t value);

  public:
  // uint64 environment_size = 6;
  void clear_environment_size() ;
  ::uint64_t environment_size() const;
  void set_environment_size(::uint64_t value);

  private:
  ::uint64_t _internal_environment_size() const;
  void _internal_set_environment_size(::uint64_t value);

  public:
  // @@protoc_insertion_point(class_scope:task.TaskRequest)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<
      4, 10, 1,
      55, 2>
      _table_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(
        ::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                          ::google::protobuf::Arena* arena);
    inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                          ::google::protobuf::Arena* arena, const Impl_& from,
                          const TaskRequest& from_msg);
    ::google::protobuf::RepeatedPtrField< ::task::EnvArrayField > arrays_;
    ::google::protobuf::internal::ArenaStringPtr environment_data_;
    ::google::protobuf::internal::ArenaStringPtr function_name_;
    ::google::protobuf::internal::ArenaStringPtr ir_data_;
    ::google::protobuf::internal::ArenaStringPtr ir_format_;
    ::int64_t task_id_;
    ::int64_t start_;
    ::int64_t end_;
    ::int64_t step_;
    ::uint64_t environment_size_;
    ::google::protobuf::internal::CachedSize _cached_size_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_task_5fservice_2eproto;
};

// ===================================================================




// ===================================================================


#ifdef __GNUC__
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// -------------------------------------------------------------------

// TaskRequest

// int64 task_id = 1;
inline void TaskRequest::clear_task_id() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.task_id_ = ::int64_t{0};
}
inline ::int64_t TaskRequest::task_id() const {
  // @@protoc_insertion_point(field_get:task.TaskRequest.task_id)
  return _internal_task_id();
}
inline void TaskRequest::set_task_id(::int64_t value) {
  _internal_set_task_id(value);
  // @@protoc_insertion_point(field_set:task.TaskRequest.task_id)
}
inline ::int64_t TaskRequest::_internal_task_id() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.task_id_;
}
inline void TaskRequest::_internal_set_task_id(::int64_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.task_id_ = value;
}

// int64 start = 2;
inline void TaskRequest::clear_start() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.start_ = ::int64_t{0};
}
inline ::int64_t TaskRequest::start() const {
  // @@protoc_insertion_point(field_get:task.TaskRequest.start)
  return _internal_start();
}
inline void TaskRequest::set_start(::int64_t value) {
  _internal_set_start(value);
  // @@protoc_insertion_point(field_set:task.TaskRequest.start)
}
inline ::int64_t TaskRequest::_internal_start() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.start_;
}
inline void TaskRequest::_internal_set_start(::int64_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.start_ = value;
}

// int64 end = 3;
inline void TaskRequest::clear_end() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.end_ = ::int64_t{0};
}
inline ::int64_t TaskRequest::end() const {
  // @@protoc_insertion_point(field_get:task.TaskRequest.end)
  return _internal_end();
}
inline void TaskRequest::set_end(::int64_t value) {
  _internal_set_end(value);
  // @@protoc_insertion_point(field_set:task.TaskRequest.end)
}
inline ::int64_t TaskRequest::_internal_end() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.end_;
}
inline void TaskRequest::_internal_set_end(::int64_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.end_ = value;
}

// int64 step = 4;
inline void TaskRequest::clear_step() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.step_ = ::int64_t{0};
}
inline ::int64_t TaskRequest::step() const {
  // @@protoc_insertion_point(field_get:task.TaskRequest.step)
  return _internal_step();
}
inline void TaskRequest::set_step(::int64_t value) {
  _internal_set_step(value);
  // @@protoc_insertion_point(field_set:task.TaskRequest.step)
}
inline ::int64_t TaskRequest::_internal_step() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.step_;
}
inline void TaskRequest::_internal_set_step(::int64_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.step_ = value;
}

// bytes environment_data = 5;
inline void TaskRequest::clear_environment_data() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.environment_data_.ClearToEmpty();
}
inline const std::string& TaskRequest::environment_data() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:task.TaskRequest.environment_data)
  return _internal_environment_data();
}
template <typename Arg_, typename... Args_>
inline PROTOBUF_ALWAYS_INLINE void TaskRequest::set_environment_data(Arg_&& arg,
                                                     Args_... args) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.environment_data_.SetBytes(static_cast<Arg_&&>(arg), args..., GetArena());
  // @@protoc_insertion_point(field_set:task.TaskRequest.environment_data)
}
inline std::string* TaskRequest::mutable_environment_data() ABSL_ATTRIBUTE_LIFETIME_BOUND {
  std::string* _s = _internal_mutable_environment_data();
  // @@protoc_insertion_point(field_mutable:task.TaskRequest.environment_data)
  return _s;
}
inline const std::string& TaskRequest::_internal_environment_data() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.environment_data_.Get();
}
inline void TaskRequest::_internal_set_environment_data(const std::string& value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.environment_data_.Set(value, GetArena());
}
inline std::string* TaskRequest::_internal_mutable_environment_data() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _impl_.environment_data_.Mutable( GetArena());
}
inline std::string* TaskRequest::release_environment_data() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:task.TaskRequest.environment_data)
  return _impl_.environment_data_.Release();
}
inline void TaskRequest::set_allocated_environment_data(std::string* value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.environment_data_.SetAllocated(value, GetArena());
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString() && _impl_.environment_data_.IsDefault()) {
    _impl_.environment_data_.Set("", GetArena());
  }
  // @@protoc_insertion_point(field_set_allocated:task.TaskRequest.environment_data)
}

// uint64 environment_size = 6;
inline void TaskRequest::clear_environment_size() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.environment_size_ = ::uint64_t{0u};
}
inline ::uint64_t TaskRequest::environment_size() const {
  // @@protoc_insertion_point(field_get:task.TaskRequest.environment_size)
  return _internal_environment_size();
}
inline void TaskRequest::set_environment_size(::uint64_t value) {
  _internal_set_environment_size(value);
  // @@protoc_insertion_point(field_set:task.TaskRequest.environment_size)
}
inline ::uint64_t TaskRequest::_internal_environment_size() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.environment_size_;
}
inline void TaskRequest::_internal_set_environment_size(::uint64_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.environment_size_ = value;
}

// string function_name = 7;
inline void TaskRequest::clear_function_name() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.function_name_.ClearToEmpty();
}
inline const std::string& TaskRequest::function_name() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:task.TaskRequest.function_name)
  return _internal_function_name();
}
template <typename Arg_, typename... Args_>
inline PROTOBUF_ALWAYS_INLINE void TaskRequest::set_function_name(Arg_&& arg,
                                                     Args_... args) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.function_name_.Set(static_cast<Arg_&&>(arg), args..., GetArena());
  // @@protoc_insertion_point(field_set:task.TaskRequest.function_name)
}
inline std::string* TaskRequest::mutable_function_name() ABSL_ATTRIBUTE_LIFETIME_BOUND {
  std::string* _s = _internal_mutable_function_name();
  // @@protoc_insertion_point(field_mutable:task.TaskRequest.function_name)
  return _s;
}
inline const std::string& TaskRequest::_internal_function_name() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.function_name_.Get();
}
inline void TaskRequest::_internal_set_function_name(const std::string& value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.function_name_.Set(value, GetArena());
}
inline std::string* TaskRequest::_internal_mutable_function_name() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _impl_.function_name_.Mutable( GetArena());
}
inline std::string* TaskRequest::release_function_name() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:task.TaskRequest.function_name)
  return _impl_.function_name_.Release();
}
inline void TaskRequest::set_allocated_function_name(std::string* value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.function_name_.SetAllocated(value, GetArena());
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString() && _impl_.function_name_.IsDefault()) {
    _impl_.function_name_.Set("", GetArena());
  }
  // @@protoc_insertion_point(field_set_allocated:task.TaskRequest.function_name)
}

// bytes ir_data = 8;
inline void TaskRequest::clear_ir_data() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.ir_data_.ClearToEmpty();
}
inline const std::string& TaskRequest::ir_data() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:task.TaskRequest.ir_data)
  return _internal_ir_data();
}
template <typename Arg_, typename... Args_>
inline PROTOBUF_ALWAYS_INLINE void TaskRequest::set_ir_data(Arg_&& arg,
                                                     Args_... args) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.ir_data_.SetBytes(static_cast<Arg_&&>(arg), args..., GetArena());
  // @@protoc_insertion_point(field_set:task.TaskRequest.ir_data)
}
inline std::string* TaskRequest::mutable_ir_data() ABSL_ATTRIBUTE_LIFETIME_BOUND {
  std::string* _s = _internal_mutable_ir_data();
  // @@protoc_insertion_point(field_mutable:task.TaskRequest.ir_data)
  return _s;
}
inline const std::string& TaskRequest::_internal_ir_data() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.ir_data_.Get();
}
inline void TaskRequest::_internal_set_ir_data(const std::string& value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.ir_data_.Set(value, GetArena());
}
inline std::string* TaskRequest::_internal_mutable_ir_data() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _impl_.ir_data_.Mutable( GetArena());
}
inline std::string* TaskRequest::release_ir_data() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:task.TaskRequest.ir_data)
  return _impl_.ir_data_.Release();
}
inline void TaskRequest::set_allocated_ir_data(std::string* value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.ir_data_.SetAllocated(value, GetArena());
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString() && _impl_.ir_data_.IsDefault()) {
    _impl_.ir_data_.Set("", GetArena());
  }
  // @@protoc_insertion_point(field_set_allocated:task.TaskRequest.ir_data)
}

// string ir_format = 9;
inline void TaskRequest::clear_ir_format() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.ir_format_.ClearToEmpty();
}
inline const std::string& TaskRequest::ir_format() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:task.TaskRequest.ir_format)
  return _internal_ir_format();
}
template <typename Arg_, typename... Args_>
inline PROTOBUF_ALWAYS_INLINE void TaskRequest::set_ir_format(Arg_&& arg,
                                                     Args_... args) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.ir_format_.Set(static_cast<Arg_&&>(arg), args..., GetArena());
  // @@protoc_insertion_point(field_set:task.TaskRequest.ir_format)
}
inline std::string* TaskRequest::mutable_ir_format() ABSL_ATTRIBUTE_LIFETIME_BOUND {
  std::string* _s = _internal_mutable_ir_format();
  // @@protoc_insertion_point(field_mutable:task.TaskRequest.ir_format)
  return _s;
}
inline const std::string& TaskRequest::_internal_ir_format() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.ir_format_.Get();
}
inline void TaskRequest::_internal_set_ir_format(const std::string& value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.ir_format_.Set(value, GetArena());
}
inline std::string* TaskRequest::_internal_mutable_ir_format() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _impl_.ir_format_.Mutable( GetArena());
}
inline std::string* TaskRequest::release_ir_format() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:task.TaskRequest.ir_format)
  return _impl_.ir_format_.Release();
}
inline void TaskRequest::set_allocated_ir_format(std::string* value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.ir_format_.SetAllocated(value, GetArena());
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString() && _impl_.ir_format_.IsDefault()) {
    _impl_.ir_format_.Set("", GetArena());
  }
  // @@protoc_insertion_point(field_set_allocated:task.TaskRequest.ir_format)
}

// repeated .task.EnvArrayField arrays = 10;
inline int TaskRequest::_internal_arrays_size() const {
  return _internal_arrays().size();
}
inline int TaskRequest::arrays_size() const {
  return _internal_arrays_size();
}
inline void TaskRequest::clear_arrays() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.arrays_.Clear();
}
inline ::task::EnvArrayField* TaskRequest::mutable_arrays(int index)
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_mutable:task.TaskRequest.arrays)
  return _internal_mutable_arrays()->Mutable(index);
}
inline ::google::protobuf::RepeatedPtrField<::task::EnvArrayField>* TaskRequest::mutable_arrays()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_mutable_list:task.TaskRequest.arrays)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _internal_mutable_arrays();
}
inline const ::task::EnvArrayField& TaskRequest::arrays(int index) const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:task.TaskRequest.arrays)
  return _internal_arrays().Get(index);
}
inline ::task::EnvArrayField* TaskRequest::add_arrays() ABSL_ATTRIBUTE_LIFETIME_BOUND {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::task::EnvArrayField* _add = _internal_mutable_arrays()->Add();
  // @@protoc_insertion_point(field_add:task.TaskRequest.arrays)
  return _add;
}
inline const ::google::protobuf::RepeatedPtrField<::task::EnvArrayField>& TaskRequest::arrays() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_list:task.TaskRequest.arrays)
  return _internal_arrays();
}
inline const ::google::protobuf::RepeatedPtrField<::task::EnvArrayField>&
TaskRequest::_internal_arrays() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.arrays_;
}
inline ::google::protobuf::RepeatedPtrField<::task::EnvArrayField>*
TaskRequest::_internal_mutable_arrays() {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return &_impl_.arrays_;
}

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// TaskResponse

// int64 task_id = 1;
inline void TaskResponse::clear_task_id() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.task_id_ = ::int64_t{0};
}
inline ::int64_t TaskResponse::task_id() const {
  // @@protoc_insertion_point(field_get:task.TaskResponse.task_id)
  return _internal_task_id();
}
inline void TaskResponse::set_task_id(::int64_t value) {
  _internal_set_task_id(value);
  // @@protoc_insertion_point(field_set:task.TaskResponse.task_id)
}
inline ::int64_t TaskResponse::_internal_task_id() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.task_id_;
}
inline void TaskResponse::_internal_set_task_id(::int64_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.task_id_ = value;
}

// bool success = 2;
inline void TaskResponse::clear_success() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.success_ = false;
}
inline bool TaskResponse::success() const {
  // @@protoc_insertion_point(field_get:task.TaskResponse.success)
  return _internal_success();
}
inline void TaskResponse::set_success(bool value) {
  _internal_set_success(value);
  // @@protoc_insertion_point(field_set:task.TaskResponse.success)
}
inline bool TaskResponse::_internal_success() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.success_;
}
inline void TaskResponse::_internal_set_success(bool value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.success_ = value;
}

// bytes result_data = 3;
inline void TaskResponse::clear_result_data() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.result_data_.ClearToEmpty();
}
inline const std::string& TaskResponse::result_data() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:task.TaskResponse.result_data)
  return _internal_result_data();
}
template <typename Arg_, typename... Args_>
inline PROTOBUF_ALWAYS_INLINE void TaskResponse::set_result_data(Arg_&& arg,
                                                     Args_... args) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.result_data_.SetBytes(static_cast<Arg_&&>(arg), args..., GetArena());
  // @@protoc_insertion_point(field_set:task.TaskResponse.result_data)
}
inline std::string* TaskResponse::mutable_result_data() ABSL_ATTRIBUTE_LIFETIME_BOUND {
  std::string* _s = _internal_mutable_result_data();
  // @@protoc_insertion_point(field_mutable:task.TaskResponse.result_data)
  return _s;
}
inline const std::string& TaskResponse::_internal_result_data() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.result_data_.Get();
}
inline void TaskResponse::_internal_set_result_data(const std::string& value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.result_data_.Set(value, GetArena());
}
inline std::string* TaskResponse::_internal_mutable_result_data() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _impl_.result_data_.Mutable( GetArena());
}
inline std::string* TaskResponse::release_result_data() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:task.TaskResponse.result_data)
  return _impl_.result_data_.Release();
}
inline void TaskResponse::set_allocated_result_data(std::string* value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.result_data_.SetAllocated(value, GetArena());
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString() && _impl_.result_data_.IsDefault()) {
    _impl_.result_data_.Set("", GetArena());
  }
  // @@protoc_insertion_point(field_set_allocated:task.TaskResponse.result_data)
}

// uint64 result_size = 4;
inline void TaskResponse::clear_result_size() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.result_size_ = ::uint64_t{0u};
}
inline ::uint64_t TaskResponse::result_size() const {
  // @@protoc_insertion_point(field_get:task.TaskResponse.result_size)
  return _internal_result_size();
}
inline void TaskResponse::set_result_size(::uint64_t value) {
  _internal_set_result_size(value);
  // @@protoc_insertion_point(field_set:task.TaskResponse.result_size)
}
inline ::uint64_t TaskResponse::_internal_result_size() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.result_size_;
}
inline void TaskResponse::_internal_set_result_size(::uint64_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.result_size_ = value;
}

// string error_message = 5;
inline void TaskResponse::clear_error_message() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.error_message_.ClearToEmpty();
}
inline const std::string& TaskResponse::error_message() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:task.TaskResponse.error_message)
  return _internal_error_message();
}
template <typename Arg_, typename... Args_>
inline PROTOBUF_ALWAYS_INLINE void TaskResponse::set_error_message(Arg_&& arg,
                                                     Args_... args) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.error_message_.Set(static_cast<Arg_&&>(arg), args..., GetArena());
  // @@protoc_insertion_point(field_set:task.TaskResponse.error_message)
}
inline std::string* TaskResponse::mutable_error_message() ABSL_ATTRIBUTE_LIFETIME_BOUND {
  std::string* _s = _internal_mutable_error_message();
  // @@protoc_insertion_point(field_mutable:task.TaskResponse.error_message)
  return _s;
}
inline const std::string& TaskResponse::_internal_error_message() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.error_message_.Get();
}
inline void TaskResponse::_internal_set_error_message(const std::string& value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.error_message_.Set(value, GetArena());
}
inline std::string* TaskResponse::_internal_mutable_error_message() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _impl_.error_message_.Mutable( GetArena());
}
inline std::string* TaskResponse::release_error_message() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:task.TaskResponse.error_message)
  return _impl_.error_message_.Release();
}
inline void TaskResponse::set_allocated_error_message(std::string* value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.error_message_.SetAllocated(value, GetArena());
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString() && _impl_.error_message_.IsDefault()) {
    _impl_.error_message_.Set("", GetArena());
  }
  // @@protoc_insertion_point(field_set_allocated:task.TaskResponse.error_message)
}

// map<int64, bytes> iteration_outputs = 6;
inline int TaskResponse::_internal_iteration_outputs_size() const {
  return _internal_iteration_outputs().size();
}
inline int TaskResponse::iteration_outputs_size() const {
  return _internal_iteration_outputs_size();
}
inline void TaskResponse::clear_iteration_outputs() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.iteration_outputs_.Clear();
}
inline const ::google::protobuf::Map<::int64_t, std::string>& TaskResponse::_internal_iteration_outputs() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.iteration_outputs_.GetMap();
}
inline const ::google::protobuf::Map<::int64_t, std::string>& TaskResponse::iteration_outputs() const ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_map:task.TaskResponse.iteration_outputs)
  return _internal_iteration_outputs();
}
inline ::google::protobuf::Map<::int64_t, std::string>* TaskResponse::_internal_mutable_iteration_outputs() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _impl_.iteration_outputs_.MutableMap();
}
inline ::google::protobuf::Map<::int64_t, std::string>* TaskResponse::mutable_iteration_outputs() ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_mutable_map:task.TaskResponse.iteration_outputs)
  return _internal_mutable_iteration_outputs();
}

// repeated .task.EnvArrayField arrays = 7;
inline int TaskResponse::_internal_arrays_size() const {
  return _internal_arrays().size();
}
inline int TaskResponse::arrays_size() const {
  return _internal_arrays_size();
}
inline void TaskResponse::clear_arrays() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.arrays_.Clear();
}
inline ::task::EnvArrayField* TaskResponse::mutable_arrays(int index)
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_mutable:task.TaskResponse.arrays)
  return _internal_mutable_arrays()->Mutable(index);
}
inline ::google::protobuf::RepeatedPtrField<::task::EnvArrayField>* TaskResponse::mutable_arrays()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_mutable_list:task.TaskResponse.arrays)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _internal_mutable_arrays();
}
inline const ::task::EnvArrayField& TaskResponse::arrays(int index) const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:task.TaskResponse.arrays)
  return _internal_arrays().Get(index);
}
inline ::task::EnvArrayField* TaskResponse::add_arrays() ABSL_ATTRIBUTE_LIFETIME_BOUND {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::task::EnvArrayField* _add = _internal_mutable_arrays()->Add();
  // @@protoc_insertion_point(field_add:task.TaskResponse.arrays)
  return _add;
}
inline const ::google::protobuf::RepeatedPtrField<::task::EnvArrayField>& TaskResponse::arrays() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_list:task.TaskResponse.arrays)
  return _internal_arrays();
}
inline const ::google::protobuf::RepeatedPtrField<::task::EnvArrayField>&
TaskResponse::_internal_arrays() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.arrays_;
}
inline ::google::protobuf::RepeatedPtrField<::task::EnvArrayField>*
TaskResponse::_internal_mutable_arrays() {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return &_impl_.arrays_;
}

// -------------------------------------------------------------------

// EnvArrayField

// uint32 field_index = 1;
inline void EnvArrayField::clear_field_index() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.field_index_ = 0u;
}
inline ::uint32_t EnvArrayField::field_index() const {
  // @@protoc_insertion_point(field_get:task.EnvArrayField.field_index)
  return _internal_field_index();
}
inline void EnvArrayField::set_field_index(::uint32_t value) {
  _internal_set_field_index(value);
  // @@protoc_insertion_point(field_set:task.EnvArrayField.field_index)
}
inline ::uint32_t EnvArrayField::_internal_field_index() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.field_index_;
}
inline void EnvArrayField::_internal_set_field_index(::uint32_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.field_index_ = value;
}

// uint64 length = 2;
inline void EnvArrayField::clear_length() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.length_ = ::uint64_t{0u};
}
inline ::uint64_t EnvArrayField::length() const {
  // @@protoc_insertion_point(field_get:task.EnvArrayField.length)
  return _internal_length();
}
inline void EnvArrayField::set_length(::uint64_t value) {
  _internal_set_length(value);
  // @@protoc_insertion_point(field_set:task.EnvArrayField.length)
}
inline ::uint64_t EnvArrayField::_internal_length() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.length_;
}
inline void EnvArrayField::_internal_set_length(::uint64_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.length_ = value;
}

// bytes data = 3;
inline void EnvArrayField::clear_data() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.data_.ClearToEmpty();
}
inline const std::string& EnvArrayField::data() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:task.EnvArrayField.data)
  return _internal_data();
}
template <typename Arg_, typename... Args_>
inline PROTOBUF_ALWAYS_INLINE void EnvArrayField::set_data(Arg_&& arg,
                                                     Args_... args) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.data_.SetBytes(static_cast<Arg_&&>(arg), args..., GetArena());
  // @@protoc_insertion_point(field_set:task.EnvArrayField.data)
}
inline std::string* EnvArrayField::mutable_data() ABSL_ATTRIBUTE_LIFETIME_BOUND {
  std::string* _s = _internal_mutable_data();
  // @@protoc_insertion_point(field_mutable:task.EnvArrayField.data)
  return _s;
}
inline const std::string& EnvArrayField::_internal_data() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.data_.Get();
}
inline void EnvArrayField::_internal_set_data(const std::string& value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.data_.Set(value, GetArena());
}
inline std::string* EnvArrayField::_internal_mutable_data() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _impl_.data_.Mutable( GetArena());
}
inline std::string* EnvArrayField::release_data() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:task.EnvArrayField.data)
  return _impl_.data_.Release();
}
inline void EnvArrayField::set_allocated_data(std::string* value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.data_.SetAllocated(value, GetArena());
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString() && _impl_.data_.IsDefault()) {
    _impl_.data_.Set("", GetArena());
  }
  // @@protoc_insertion_point(field_set_allocated:task.EnvArrayField.data)
}

#ifdef __GNUC__
#pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)
}  // namespace task


// @@protoc_insertion_point(global_scope)

#include "google/protobuf/port_undef.inc"

#endif  // task_5fservice_2eproto_2epb_2eh
